### ISSUE TITLE
为什么把DOM节点插入到body节点之外

### ISSUE THREAD

**Issue by jasonChen1982** [Tencent/vConsole#100]
在使用`vconsole`的时候发现页面的高度增加了，检查`dom`节点发现，生成的`DOM`节点是被添加到了`body`之外，导致在有些浏览器上视口改变时按钮被截断
![image](https://cloud.githubusercontent.com/assets/8683772/26050804/abde868a-3992-11e7-9129-0767ef171e05.png)

**Comment by Maizify** [comment]
是什么浏览器呢？
是否是CSS设置了溢出截断？

**Comment by sxd1140** [comment]
QQ浏览器
`版本 4.2.4718.400 (64-bit)`
`内核 Chromium 54.0.2840.98`

**Comment by Maizify** [comment]
这是为了尽可能避免影响body内的节点更新及样式渲染。
其实插里面插外面都很难完全避免这个情况，楼主可以先修改下页面样式以避免冲突。
