### ISSUE TITLE
vConsole按钮被隐藏

### ISSUE THREAD

**Issue by yuanhaoyu** [Tencent/vConsole#103]
当内元素超过屏幕宽度时，vConsole按钮会被隐藏（当宽度相等有overflow:hidden类似的效果）

目前存在问题的浏览器：微信 v6.5.8 自带浏览器 ， uc浏览器 v11.5.2.942

（chrome v 58.0.3029.83 使用正常）

**Comment by Maizify** [comment]
请问有无实例看一下？

**Comment by yuanhaoyu** [comment]
http://llamastudio.cn/test2/1.html

安卓测试

[uc图片](http://llamastudio.cn/test2/21E360EF5BA6D305A49C3A3F508C62D7.jpg)

[wchat图片](http://llamastudio.cn/test2/CD9DCD23D668DBF76B5D0BEB47B32BB9.jpg)
