### ISSUE TITLE
Network 无法显示出请求，一直是empty

### ISSUE THREAD

**Issue by hanxiansen** [Tencent/vConsole#111]
描述如题，一直都是empty，不知是什么原因。

**Comment by hwygy001** [comment]
我也遇到了，是不是通过fetch发送的请求，之前xhr可以，最近改成fetch就抓不到了

**Comment by wangyao92** [comment]
我用的是axios  ，也不行  请求返回的一直是 [object Undefined]

**Comment by jiajunlin** [comment]
也是用axios，请求一直返回undefined

**Comment by Maizify** [comment]
v3.0.0已处理。
