### ISSUE TITLE
Network中面板中的请求状态：用vue-resource是正常的，用axios一直是pending

### ISSUE THREAD

**Issue by tonyfree** [Tencent/vConsole#113]
如题，使用axios时，
对vconsole.min.js源码打断点测试，readyState都是1
版本说明：  
vconsole ^2.5.2
axios ^0.16.1
vue-resource ^1.2.0

**Comment by jiajunlin** [comment]
也是遇到同样的情况

**Comment by arno-react** [comment]
axios 封装     request.open 执行和 request.onreadystatechange 赋方法的 先后顺序问题
vconsole 的request.onreadystatechange的切面 在request.open执行时赋的
然axios  request.open 执行后才 request.onreadystatechange 赋方法 导致vconsole的切面被覆盖了。
修改 axios包中的 xhr.js 
把`request.open(config.method.toUpperCase(), buildURL(config.url, config.params, config.paramsSerializer), true);`
移到
`request[loadEvent] = function handleLoad() {......}`
后面

**Comment by Maizify** [comment]
@arno-react 赞，这个问题我也发现了，为了避免修改外部库，现在 v3.0.0 的做法是使用 setInterval 来避免被外部覆盖。如有更优雅的办法，欢迎交流~

**Comment by arno-react** [comment]
我在open  内改写  XMLReq.onreadystatechange的 set方法   ，先保存开始的开始的set方法。再把onreadystatechange定个方法，
当第3方库 修改onreadystatechange方法时  再执行我们定的onreadystatechange 方法。把第3方库传进去。
   `var oldFn = XMLReq.__proto__.__lookupSetter__('onreadystatechange')
      XMLReq.__proto__.__defineSetter__("onreadystatechange", function (val) {
        onreadystatechange.call(that,val)
      })`

定义的onreadystatechange 方法
  再把XMLReq.onreadystatechange的 set方法 改成开始的，保证这次修改不会再执行onreadystatechange方法
` function onreadystatechange(fn) {
        XMLReq.__proto__.__defineSetter__("onreadystatechange", old)
        // let _onreadystatechange = XMLReq.onreadystatechange || function () {
        //   };
        let _onreadystatechange = fn || function () {
          };
        XMLReq.onreadystatechange = function () {.....}`
