### ISSUE TITLE
华为p9的uc浏览器,使用console的log方法log一些信息的时候,会卡死浏览器

### ISSUE THREAD

**Issue by wweggplant** [Tencent/vConsole#116]
如题
环境:华为p9,安卓版本7.0
添加vconsole后,在代码中log一些稍微复杂的对象就卡死, 取掉vconsole后一切正常

**Comment by Maizify** [comment]
当前版本是有这样的bug，预计之后修复。

**Comment by wweggplant** [comment]
@Maizify  看到更新了,请教下什么时候3.0能发布到npm上?

**Comment by Maizify** [comment]
@wweggplant 3.0.0还有些bug没搞完，可能要再晚一点点。

**Comment by Maizify** [comment]
v3.0.0已处理。
