### ISSUE TITLE
android4.4 和ios8中跨域的get请求network中一直是pending状态

### ISSUE THREAD

**Issue by npm-ued** [Tencent/vConsole#118]
如题，
使用vConsole 3.0.0 跨域的get请求在面板中一直是pending状态，使用charles也无法抓取到数据包，post请求正常，不知道是使用上有错误？

**Comment by Maizify** [comment]
有无实例看一下？

**Comment by npm-ued** [comment]
找到问题了，clone源码本地修改了下，我可以修改合并到主分支上么？问题出转译ES6上，导致代码没有正常运行

**Comment by Maizify** [comment]
可以提一个Pull request到dev分支看看。

**Comment by npm-ued** [comment]
@Maizify https://github.com/Tencent/vConsole/pull/119 通过添加babel-polyfill依赖修复低版本不支持Symbol修复，修改的比较粗糙

**Comment by npm-ued** [comment]
@Maizify 合并一下使用者使用的更方便
