### ISSUE TITLE
是否可以不通过 console.log 向 vConsole 输出日志？

### ISSUE THREAD

**Issue by JasinYip** [Tencent/vConsole#124]
我们有一些通过某种方式保存下来的日志，希望再吐到 vConsole 当中，不知道有没有什么方法可以直接向 vConsole 输出日志？

**Comment by Maizify** [comment]
暂无，只能通过 console.log / console.info / console.debug / console.error 这种形式输出。

**Comment by JasinYip** [comment]
是未来都不会有吗？如果暂时没有我可以看看能不能 fork 后实现一下，如果跟你们的设计有冲突的话就不发 PR 了

**Comment by Maizify** [comment]
暂时没有，不过可以考虑增加个新接口，还挺简单的。

**Comment by JasinYip** [comment]
我预想 API 是通过像 `vConsole.log`、`vConsole.error` 这样来调用的。

我看了下源码，要实现倒是简单，不过我看现在代码是把 log 作为 plugin 通过 `addPlugin` 方法加进去的，实现了解耦，比较优雅。但是如果说我们在 `VConsole` 类中直接添加 `log/error` 方法，然后通过 `this.pluginList.default.printLog` 实现的话，可能会使 core 和 log plugin 耦合了。

不知道你们是怎么考虑的？是觉得这样还 ok，还是说打算给 plugins 开放 methods 注册的机制？后者实现起来成本可能会更高一些

**Comment by Maizify** [comment]
简单实现的话，预计是通过类似 `vConsole.print()` 的方法来调用。这个 `print()` 方法会在 log plugin 里实现，并将它挂载到 `VConsole` 原型中。因为 log plugin 本身就是必须加载的内置插件，所以稍有耦合应该还可以接受。
长远来看的话，像你说的给 plugin 开放 methods 的注册机制，应该是个不错的办法。

**Comment by YangYongAn** [comment]
现在这个问题有什么最优解了吗

**Comment by Maizify** [comment]
已在3.11.0中支持。
```
vConsole.log.log(...);
vConsole.system.log(...);
```

**Comment by YangYongAn** [comment]
不错
