### ISSUE TITLE
编译的时候，vconsole.min.js报错是什么为什么呢？

### ISSUE THREAD

**Issue by margin-0** [Tencent/vConsole#127]
您好，编译的时候出现vconsole报错，更新之前是好的，报错如下
![251510907143_ pic_hd](https://user-images.githubusercontent.com/23308724/32937739-98af752e-cbb4-11e7-86b7-8823fb72af9c.jpg)
运用于： react + webpack +es6
vconsole 版本是 2.5.2 或者3.0.0 也不行
请问这是什么原因呢？

**Comment by Maizify** [comment]
这里看不出什么问题。之前用什么版本的vConsole可以通过？

**Comment by margin-0** [comment]
之前是可以的

**Comment by Maizify** [comment]
之前用什么版本的vConsole可以通过？

**Comment by margin-0** [comment]
<img width="404" alt="ae95c260-83e2-4c37-a108-2507ab1bdbe7" src="https://user-images.githubusercontent.com/23308724/33258904-04116c94-d396-11e7-8f23-26a74d798ca6.png">


你好，才回复，我和同事查询之后把
```js
'plugins': ['add-moudlu-exports']
```

设置注释了之后就可以了

**Comment by Maizify** [comment]
没问题了就行。虽然vConsole里好像没这段配置……
