### ISSUE TITLE
为什么network里没数据

### ISSUE THREAD

**Issue by 493843643** [Tencent/vConsole#128]
为什么network里抓不到数据，显示为空，还是说要在request的时候注入代码么。。新人求解，谢谢~！

**Comment by Maizify** [comment]
用的是哪个版本的vConsole？另外有用别的第三方网络框架吗？

**Comment by 493843643** [comment]
最新的3.0.0版本，没有别的第三方网络框架。。

**Comment by 493843643** [comment]
而且我用你的demo1页面也没network日志。。难道是我nginx的问题？

**Comment by 493843643** [comment]
我知道了，只能抓同域的get和post，没法抓跨域请求的数据.。。

**Comment by Maizify** [comment]
是的，跨域请求走的不是XHR，目前还抓不到。

**Comment by PanJs** [comment]
我走的代理，没有跨域也抓不到请求
