### ISSUE TITLE
引入两次会有问题，能做下去重判断吗？

### ISSUE THREAD

**Issue by diamont1001** [Tencent/vConsole#130]
![image](https://user-images.githubusercontent.com/7159888/33758785-c6ad4870-dc3a-11e7-83d9-8b3bdb6eb73a.png)

相关 ISSUE：[https://github.com/diamont1001/vconsole-webpack-plugin/issues/6](https://github.com/diamont1001/vconsole-webpack-plugin/issues/6)

**Comment by Maizify** [comment]
这是哪个版本的vConsole？

**Comment by diamont1001** [comment]
不好意思，刚试了下好像没问题
