### ISSUE TITLE
微信小程序 vConsole 将已清除掉的log记录再次打印出来，造成代码没有生效或者微信扫码错误的错觉

### ISSUE THREAD

**Issue by Dragon-Rider** [Tencent/vConsole#131]
可能是个bug。

具体的问题详细描述请见：https://github.com/find-xcx-bugs/xcx-bug-list/blob/master/docs/5-vConsole.md

谢谢。

**Comment by Maizify** [comment]
谢谢反馈，这是小程序底层的一个问题，正在修复中，不是vConsole的问题哈。
