### ISSUE TITLE
在支付宝客户端报script error这个错误

### ISSUE THREAD

**Issue by TheOneHomles** [Tencent/vConsole#133]
支付宝扫描二维码进入我的网站，然后报错：script error

**Comment by TheOneHomles** [comment]
已解决.

**Comment by liujianxi** [comment]
项目引入了微信的sdk，是不能在支付宝打开的，应该是支付宝禁止了




| |
刘建喜
邮箱：13380360847@163.com
|

签名由 网易邮箱大师 定制

在2018年05月24日 18:08，瞿宝明 写道：

@liujianxi 你好，请问你怎么解决的？
