### ISSUE TITLE
vconsole在低版本的ios不支持的问题

### ISSUE THREAD

**Issue by guozhenqianga** [Tencent/vConsole#140]
项目中引用了vconsoejs,大部分ios和Android使用正常，但是在低版本ios出现了vconsolejs报错的问题，怀疑是vconsojs不支持的问题，因为vconsolejs采用的es6的语法，低版本的ios不吃之es6的语法，我将vconsole.min.js用babel-5.x转化之后依然不能用
报错内容
![_fi21 iwh1 wa4 vv zf k](https://user-images.githubusercontent.com/23112360/34473648-59b35438-efb0-11e7-80f4-a6d776c8bae5.png)

**Comment by Maizify** [comment]
对iOS8的兼容是不太好。能定位到更详细的错误点吗？

**Comment by pandashuai** [comment]
在华为手机中，低版本也会出现不支持的现状，关注中，求解

**Comment by yuanyayi** [comment]
iOS9.3.2，右下按钮没有显示。
