### ISSUE TITLE
华为P8页面使用vConsole只能加载页面，但是页面内的post请求无法发出，一直pending

### ISSUE THREAD

**Issue by sunlianlong** [Tencent/vConsole#142]
手机类型：华为P8
型号：ALE-TL00
Android版本：5.0.2
系统版本：EMUI系统3.1

页面使用vue2.0 vue-cli 构建 生产版本

表现：使用浏览器可以访问页面，JS、CSS、IMAGES都可以正常加载，但是使用axios发出的post请求无法发送到目标服务器，vconsole看到network里面请求的status一直为pending
 
备注：大部分手机可以，但是有一部分android机会出现这种情况，魅族之前有一款没有记住型号也是这种情况。

**Comment by Maizify** [comment]
哪个版本的vConsole？

**Comment by sunlianlong** [comment]
3.0.0

**Comment by Maizify** [comment]
有没有用什么js框架或ajax库？

**Comment by sunlianlong** [comment]
使用了vue 版本为 2.1.8  http请求使用axios 版本是 0.15.3

**Comment by fireyy** [comment]
试试看 #156 是否解决了这个问题
