### ISSUE TITLE
请问android最低兼容的版本是多少

### ISSUE THREAD

**Issue by plmmanwu** [Tencent/vConsole#143]
放到android4.2的手机上没有任何反应，请问android最低兼容的版本是多少

**Comment by hubcarl** [comment]
4.2 上面 undefined is not function

**Comment by KevisLuo** [comment]
@Maizify 我测试了一下是因为安卓4.2不支持MutationObserver，查了下资料MutationObserver从4.4开始才支持的

**Comment by Maizify** [comment]
@KevisLuo 感谢查证

**Comment by zhongmeizhi** [comment]
在Android 5.0以下有问题

is:issue is:open https://user-images.githubusercontent.com/17895124/58849125-bda19380-86bb-11e9-954c-b155d656b28d.png

**Comment by zhuxingyu16** [comment]
vconsole依赖MutationObserver只支持安卓4.4

**Comment by Chen0217** [comment]
为啥我安卓5.1.1 也不兼容
