### ISSUE TITLE
在支付宝内置浏览器 http 400 缓慢

### ISSUE THREAD

**Issue by kangkang07** [Tencent/vConsole#145]
使用支付宝内置浏览器，post 请求，返回状态为400的时候，vconsole的网络页面显示请求过程会长达10000ms以上，后续程序代码也被阻塞，而在XMLHTTPRequest onstatuschange上打时间会发现并没有这么久，通常一秒内就返回了。

**Comment by Maizify** [comment]
这里的逻辑都是异步的，应该不会堵塞后续代码才对。有用什么第三方库吗？

**Comment by kangkang07** [comment]
没有用什么库，原来用的axios，为了排查把它去掉了，写原生的ajax，还是一样。
而且这个问题仅出现在支付宝里面，当http状态为400的时候

**Comment by Maizify** [comment]
好的，我先查下。
