### ISSUE TITLE
Unknown plugin "add-module-exports"

### ISSUE THREAD

**Issue by ouzhou** [Tencent/vConsole#147]
node_modules/vconsole/dist/vconsole.min.js: Unknown plugin "add-module-exports" specified in /node_modules/vconsole/.babelrc" at 0, attempted to resolve relative to "node_modules/vconsole"

**Comment by Maizify** [comment]
看下 `pakage.json` 里的`devDependencies`有没有添加 `babel-plugin-add-module-exports` ？
