### ISSUE TITLE
Network里response太长时在手机上无法显示全

### ISSUE THREAD

**Issue by xilin** [Tencent/vConsole#149]
在桌面浏览器里可以用滚轮查看，在手机上没办法看全，无法滚动。

**Comment by xilin** [comment]
![img_5894](https://user-images.githubusercontent.com/543395/35721019-2e452af4-082b-11e8-9f51-1b1ec103ade9.PNG)

@Maizify 见截图，手指无法拖动

**Comment by Maizify** [comment]
我先记下了，回头测试下这种case。

**Comment by zhubenjie** [comment]
我的network里面什么都看不到， 你的为什么会有信息

**Comment by zhuanyongxigua** [comment]
这个问题解决了吗？
