### ISSUE TITLE
csp的报错vconsole看不到

### ISSUE THREAD

**Issue by yummyLcj** [Tencent/vConsole#150]
![image](https://user-images.githubusercontent.com/9097410/35904182-270592ba-0c1d-11e8-911a-05b5e1a34dac.png)
在微信6.6.2时碰到微信支付因为csp被拦截，在vconsole里看不到该错误

**Comment by Maizify** [comment]
这种错误好像并不会通过on error抛出来，如何捕获此类错误还得再想想。

**Comment by yoyo837** [comment]
保持开启呗，想不到方案之前
