### ISSUE TITLE
vue 项目集成错误

### ISSUE THREAD

**Issue by Jiiiiiin** [Tencent/vConsole#152]
集成之后：
![](https://ws2.sinaimg.cn/large/006tNc79gy1foq7drmaxuj31kw0swgwo.jpg)

安装的是latest版本；
引入方式：
```js
if (process.env.NODE_ENV !== 'production' && viewPlusOptions.debug) {
  import(/* webpackChunkName: 'vconsole' */ 'vconsole').then((VConsole) => {
    /* eslint-disable no-new */
    new VConsole()
  }).catch(err => console.error(err))
}
```

也尝试过使用require方式，也是同样问题。

**Comment by Maizify** [comment]
看起来并不像是vConsole的错误呀？

**Comment by dolphinfine** [comment]
你不管开发还是生产环境都直接引入，然后生产环境new一个对象不就行了。

**Comment by PerseveranceZ** [comment]
我也报这个错误了 注释了 vconsole 实例就不报错

**Comment by Niofh** [comment]
怎么解决了？楼主！

**Comment by Maizify** [comment]
各位，报上述错误后，vConsole运行正常吗？

**Comment by april-1993** [comment]
遇到同样的问题，不过报错误后，vconsole运行正常， @Maizify

**Comment by hollyDysania** [comment]
@Maizify vConsole运行正常 只要是console.log Vue的$refs就会出现这个问题

**Comment by Maizify** [comment]
@hollyDysania @april-1993 可能是业务页面用console.log打印了一些复杂对象（比如vue的$refs）导致出错，可以尝试注释掉业务里的console.log再看看。

**Comment by april-1993** [comment]
@Maizify 刚尝试了一下，找到了问题所在！原因正如您所说，是我watch了$route，每次页面跳转都会console.log(to,from)，最终会不断报错。在我注释掉console后，问题就消失了！现象层面的问题算是解决了，深层次的我还不没搞清楚是为什么……

**Comment by Maizify** [comment]
@april-1993 打印的对象比较复杂就有可能出错，这个还在进一步处理中。

**Comment by april-1993** [comment]
@Maizify 上面我虽然知道在打印$route的to和from时会报错。但实际上，经过进一步测试，发现只有在打印from参数时才会报。并且，当from是根目录时是不会报“toJSON”错误的。

1. 当from为“/”时，不会报错。

![image](https://user-images.githubusercontent.com/29689307/41952080-b61b6e6a-7a00-11e8-8dbe-22e34ce28460.png)

2.当from有路由时，会报[Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render。

![image](https://user-images.githubusercontent.com/29689307/41952193-44144e44-7a01-11e8-9209-be44516c52e3.png)

**Comment by monw3c** [comment]
确实会报错，而且卡爆了

**Comment by Jason8Zhang** [comment]
我也遇到这个问题了，学习了

**Comment by zhouyu1993** [comment]
在 `$route` 发生变化，

``` js
watch: {
      '$route' (to, from) {
          console.log(to, from)
      }
},
```

或

``` js
router.beforeEach((to, from, next) => {
    console.log(to, from)
})
```

就会有问题

**Comment by pandao** [comment]
**原因：**

* 打印的对象太复杂（例如：Vue 实例对象 `this`、Circular Objects）；
* Vue 或插件的对象属性声明、引用或赋值时类型不一致；

**解决办法：**

* 不要直接整个打印 Vue 实例对象 `this` 等复杂对象，例如按需打印成员属性和方法；
* Vue Router 路由对象的 `from` 和`to` 属性需要做拷贝处理，例如: `to` 属性可以这样 `JSON.parse(JSON.stringify(to))` 直接拷贝；另外 `from` 属性比较特殊（疑似因为 `from.name` 的声明和赋值类型不一致）则需要遍历拷贝，其中 `from.matched` 属性更复杂，建议不要输出，或者做深拷贝处理；

```typescript
function vueRouteObjectCopy (route: Route): Route {
    let _route: any = {}

    for (let i in route) {
        if (typeof route[i] === 'object') {
            if (i === 'matched') {
                _route[i] = [] // 'from.matched' is circular objects, need deep copying, recommended not to print this property
            } else {
                _route[i] = Object.assign({}, route[i])
            }
        } else {
            _route[i] = route[i] || ''
        }
    }

    return _route
}
```

**Comment by zhouyu1993** [comment]
@pandao hh，确实，29天前试了一下，确实是因为【对象太复杂】。另外直接用 `JSON.parse(JSON.stringify)` 处理有的时候也会报错，毕竟这种方法对 `Function` 失效。但也可能是我用在了 `from` 上。

**Comment by pandao** [comment]
> @pandao hh，确实，29天前试了一下，确实是因为【对象太复杂】。另外直接用 `JSON.parse(JSON.stringify)` 处理有的时候也会报错，毕竟这种方法对 `Function` 失效。但也可能是我用在了 `from` 上。

这个方法不能用在 `from` 属性上。

**Comment by zhishaofei3** [comment]
嘿嘿，第一次见到这个报错，我莫名其妙，还以为是我写出来的问题

**Comment by ManfredHu** [comment]
```
vconsole.min.js?2f0e:11 [WDS] Warnings while compiling.
value @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:11
window.console.(anonymous function) @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:11
value @ vconsole.min.js?2f0e:11
window.console.(anonymous function) @ vconsole.min.js?2f0e:11
warnings @ index.js?bed3:147
onmessage @ socket.js?57b2:41
EventTarget.dispatchEvent @ sockjs.js?3600:170
(anonymous) @ sockjs.js?3600:887
SockJS._transportMessage @ sockjs.js?3600:885
EventEmitter.emit @ sockjs.js?3600:86
WebSocketTransport.ws.onmessage @ sockjs.js?3600:2961
vconsole.min.js?2f0e:11 ./src/helper/vconsole-helper.js
]50;CurrentDir=/Volumes/guo/hu-vue-plugin
  ✘  http://eslint.org/docs/rules/no-unused-vars  'vc' is assigned a value but never used  
  src/helper/vconsole-helper.js:14:13
        const vc = new VConsole()
               ^


✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/no-unused-vars
 @ ./src/index.js 7:0-48
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

我也很纠结，new VConsole()之后我不给window挂好像没办法处理了呀。eslint-config-standard配置

**Comment by MontageD** [comment]
解决了，根据楼上的方法，凡是路由生命周期里面调用的方法，如果在执行中做了打印操作都会报错..只要排除路由方法里面的打印或者外部引用方法的打印就可以了。

**Comment by regiondavid** [comment]
升级到最新的V3.3之后无报错了，可以试下

**Comment by cookcc** [comment]
不仅是路由的生命周期，在组件的生命周期中，打印复杂对象就会报这个错，我打印的对象是this.$store。综合上面遇到的情况以及自己遇到的，概括起来就是打印复杂对象会报这个错，至于什么样的对象才符合这里的复杂对象具体还不清楚，当出现这个报错，优先把console注释掉就好了

**Comment by zhouyu1993** [comment]
@cookcc 我猜测是 `vConsole` 在封装 `console` 时使用了 `JSON.stringify`，`this` 这种循环调用

JSON 格式数据存在循环调用，是会报 `Uncaught TypeError: Converting circular structure to JSON`

**Comment by ddmy** [comment]
这个问题没有fix吗

**Comment by cqupt-yifanwu** [comment]
同样的问题，确实是console了复杂对象

**Comment by zhouxitian** [comment]
今天也遇到在这个问题了。都没有好的解决办法，只能自己重写一下console避过报错的地方了。
`new vConsole()//重写方法要在new vConsole()后面
function deepArguments(arr){//这方法里不能有打印
		let parArr=[];
		let strArr=JSON.parse(JSON.stringify(arr||{}));
		strArr=Object.values(strArr);
		for(let i=strArr.length;i--;){
			let str=strArr[i];
			if((str+"").indexOf('Property or method')!==-1&&(str+"").indexOf("toJSON")!==-1){
				str=''//跳过出错项
			}
			str!==''&&parArr.unshift(str);
		}
		return parArr;
	}
	window.console=(function(wConsole={}){//重写console ，因为使用vconsole打印复杂对象时会导致报错。如打印路由切换时的 from 对象等
		return {
			log: function(){
				try{
					wConsole.log.apply(this,deepArguments(arguments))
				}catch(e){
					wConsole.log("vConsole打印复杂数据导致报错,请忽略"+(e))
				}
			},
			info : function(){
				try{
					wConsole.info.apply(this,deepArguments(arguments))
				}catch(e){
					wConsole.info("vConsole打印复杂数据导致报错,请忽略"+e)
				}
			},
			warn : function(){
				try{
					wConsole.warn.apply(this,deepArguments(arguments))
				}catch(e){
					wConsole.warn("vConsole打印复杂数据导致报错,请忽略"+e)
				}
			},
			error : function(){
				try{
					wConsole.error.apply(this,deepArguments(arguments))
				}catch(e){
					wConsole.error("vConsole打印复杂数据导致报错,请忽略"+e)
				}
			},
			time : function(){
				try{
					wConsole.time.apply(this,deepArguments(arguments))
				}catch(e){
					wConsole.time("vConsole打印复杂数据导致报错,请忽略"+e)
				}
			},
			timeEnd : function(){
				try{
					wConsole.timeEnd.apply(this,deepArguments(arguments))
				}catch(e){
					wConsole.timeEnd("vConsole打印复杂数据导致报错,请忽略"+e)
				}
			}
		};
	}(window.console));`
