### ISSUE TITLE
微信小程序集成出错

### ISSUE THREAD

**Issue by Richard-Choooou** [Tencent/vConsole#153]
提示
VM3616:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'navigator' of undefined 
 TypeError: Cannot read property 'navigator' of undefined
编辑源码
打印window，输入undefind

**Comment by Maizify** [comment]
没太明白，你是怎么集成、操作的？

**Comment by Richard-Choooou** [comment]
说来也是搞笑，我在微信小程序社区里反馈一个问题，如何获取微信基础库版本的提示是打开vconsole查看，我第一时间想到你们开发的这个工具库，结果他们说的vconsole指的是微信开发工具的调试工具。。。

**Comment by Richard-Choooou** [comment]
你还是和小程序部门的人说说吧。。。

**Comment by Maizify** [comment]
请描述下详情吧。你是在小程序内开启了vConsole，然后里面显示了上面的error？

**Comment by Richard-Choooou** [comment]
是的，应该是小程序运行时已经转换成native环境，然后就没有window了吧

**Comment by Maizify** [comment]
vConsole的环境里是有window对象的，开发者的业务代码里是没window对象的。你是否在某些地方调用了window对象呢？

**Comment by Richard-Choooou** [comment]
代码里没有调用过window，但是vconsole.js里使用过window对象，所以提示vconsole.js里出错，你可以尝试下

**Comment by Maizify** [comment]
是不是直接在自己代码里import了vConsole？

**Comment by Richard-Choooou** [comment]
是的

**Comment by Maizify** [comment]
不需要自行import vconsole，小程序底层框架已直接集成有vConsole，在右上角菜单中“打开调试”即可。

**Comment by wangxiaowen940104** [comment]
微信小程序里面可以使用vconsole.min.js吗？我也出现了同样的错误

**Comment by Maizify** [comment]
@wangxiaowen940104 不需要自行引入vconsole.min.js，小程序小游戏已经自带有vConsole了，在右上角菜单中“打开调试”即可。
