### ISSUE TITLE
支持IE吗

### ISSUE THREAD

**Issue by Leotw** [Tencent/vConsole#154]
在IE浏览器（IE10以上）的机具设备上，无法使用。可以看到vconsole的按钮，但是点击后没有反应

**Comment by Maizify** [comment]
vConsole 主要还是针对手机设备，所以还没在 IE 上做兼容性测试。
可以开 IE 自己的控制台看下是什么错误。

**Comment by smalike** [comment]
IE 浏览器支持良好组件可以使用：https://github.com/liriliri/eruda
