### ISSUE TITLE
Error: Uncaught InvalidStateError

### ISSUE THREAD

**Issue by fireyy** [Tencent/vConsole#157]
在某些android >= 5 之前的机型上，在 readyState > 1 之前获取 status 会报

```
Error: Uncaught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable.
```

错误截图

<img width="480" alt="screen shot 2018-04-04 at 4 14 42 pm" src="https://user-images.githubusercontent.com/66291/38296563-4c4deed6-3824-11e8-917d-3626bffcc939.png">

这里有一个fix #156

**Comment by Maizify** [comment]
谢谢PR，已合。
