### ISSUE TITLE
滚动查看前面的log时，总时跳到底部

### ISSUE THREAD

**Issue by WhatMakesPeopleLazy** [Tencent/vConsole#161]
vConsole.setOption({ disableLogScrolling: false });
但还是无效呢？

**Comment by Maizify** [comment]
设为 true 才是禁用此功能。

**Comment by WhatMakesPeopleLazy** [comment]
@Maizify 设置为true了，调试时，我想看前面的log，还是会按一定频率滚到底部，是否还有其他option没设置

**Comment by WhatMakesPeopleLazy** [comment]
@Maizify vconsole会按一定的频率滚到底部，并不是新日志产生的问题，测试机ios8系统

**Comment by Maizify** [comment]
记下了，我看看是不是有 bug。

**Comment by joenil** [comment]
碰到同样的问题，每个面板网上滚动后，都自动跳回底部。
