### ISSUE TITLE
network可以支持查看图片、css和js的加载时间么

### ISSUE THREAD

**Issue by html5challenge** [Tencent/vConsole#163]
现在项目中都用vconsole来做真机测试，最近需要测试时间线性能，不知道js等文件等加载时间能否看到，多谢

**Comment by Maizify** [comment]
这个暂时做不到。
因为需要在这些资源文件的 `onload` 上做打点，才可以统计出时间。这需要入侵业务代码，暂时还没特别好的办法。

**Comment by html5challenge** [comment]
明白了，多谢大牛，看来要自己加在代码里了

**Comment by Maizify** [comment]
@cocody 不太清楚TBS的情况。

**Comment by qingxiangchayun** [comment]
> 这个暂时做不到。
> 因为需要在这些资源文件的 `onload` 上做打点，才可以统计出时间。这需要入侵业务代码，暂时还没特别好的办法。

使用Performance API，应该可以做吧。只是可能会有些兼容性问题。
