### ISSUE TITLE
控制面板不会提示iframe中的报错信息

### ISSUE THREAD

**Issue by yi-jy** [Tencent/vConsole#179]
首先，非常感谢你们团队提供的这款插件。但在使用时，出现了一个无法定位的问题。

比如，页面中嵌入了 iframe，而iframe的内容页面如果有报错的话，vConsole 控制面板不会提示报错信息。

但 Chrome自带的调试控件，则会提示iframe内容的报错信息。请问有相关解决方案吗？

**Comment by Maizify** [comment]
暂时还不兼容iframe。因为现在只钩住了主页面的console方法，子页面的没有通信上来。

**Comment by colorwin** [comment]
在iframe里面重新实例化一次也不行

**Comment by awong1900** [comment]
me too,  有什么其他解决方法呢？

**Comment by KANLON** [comment]
+1
