### ISSUE TITLE
Network里如果是JSON格式，response数据不会被htmlEncode导致看不到带标签的数据

### ISSUE THREAD

**Issue by kangmo123** [Tencent/vConsole#180]
现象如下：
![image](https://user-images.githubusercontent.com/1232768/41588981-dbc850ea-73e5-11e8-86e2-b21f125ef31a.png)
Network里看response时，显示成了html元素

实际数据是：
![image](https://user-images.githubusercontent.com/1232768/41588767-38090e5e-73e5-11e8-8506-a18a01a4e782.png)

问题原因是：
![image](https://user-images.githubusercontent.com/1232768/41588860-8015854c-73e5-11e8-8e7d-757072488862.png)
不知道出于何种考量，当类型是JSON时没有像text类型一样执行htmlEncode

解决方案是：
![image](https://user-images.githubusercontent.com/1232768/41595414-482378e2-73f9-11e8-8cae-66ac5b814eeb.png)

**Comment by diaosj** [comment]
才发现是Tencent……
