### ISSUE TITLE
关于 XMLHttpRequest.onreadystatechange 重写的时机

### ISSUE THREAD

**Issue by whinc** [Tencent/vConsole#191]
network 面板中，关于 XMLHttpRequest.open 方法重写时对 onreadystatechange 的处理（[源码位置](https://github.com/Tencent/vConsole/blob/168d14571bbcb97dd7f1eb54bbaee09b57746931/src/network/network.js#L285)），有点疑问请楼主解答下。

vConsole 是在 open 方法中重写了 onreadystatechange 事件处理函数，如果用户在 open 方法之后注册 onreadystatechange 事件处理函数，会导致 open 方法内部注册的 onreadystatechange 事件处理函数被覆盖，结果是 readyState 状态变化时，无法触发 vConsole 内部的网络请求状态的变化。

看到代码后面紧接着有处理这种情况（[源码位置](https://github.com/Tencent/vConsole/blob/168d14571bbcb97dd7f1eb54bbaee09b57746931/src/network/network.js#L341)），通过定时轮训主动检测 readyState 变化来触发 vConsole 内部的 onreadystatechange 处理函数。

这里是不是有更好的处理方式：open 方法内部，如果 onreadystatechange 已注册，可以立即重写该事件的处理函数，否则将 onreadystatechange 的重写延迟到下一个微任务周期进行，这样可以省去定时轮训操作。下面是一些实现参考代码：
```javascript
const getOverrideHandler = () => {
  const _onreadystatechange = xhr.onreadystatechange || function () {}
  return function () {
    // ...
    _onreadystatechange.apply(this, arguments)
  }
}

// 如果 open() 方法调用前，onreadystatechange 已注册，可以立即重写
// 否则，在下一个微任务中重写，即等到用户注册后再执行
if (typeof xhr.onreadystatechange === 'function') {
  xhr.onreadystatechange = getOverrideHandler()
} else {
  nextTick(() => {
    xhr.onreadystatechange = getOverrideHandler()
  })
}
```

**Comment by ParadeTo** [comment]
好想法

**Comment by Maizify** [comment]
好想法，欢迎提PR~
