### ISSUE TITLE
vue 中切换路由报Property or method "toJSON" is not defined

### ISSUE THREAD

**Issue by keyubin** [Tencent/vConsole#193]
vue中 main。js 引入 
```
import Vconsole from './utils/vconsole.min.js'
// import VConsole from 'vconsole'
let option ={
  maxLogNumber:1000
}
var vConsole = new Vconsole(option);
```
路由切换时
报错 ：
`Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.`

**Comment by Jason8Zhang** [comment]
我也遇到这个问题，在安卓手机和chrome上会报这个，iOS手机上面目前木有

**Comment by Jason8Zhang** [comment]
#152 这个里面有解决方案

**Comment by zenonux** [comment]
遇到同样问题，望尽快解决啊，不然挺麻烦的

**Comment by Akimyou** [comment]
"vconsole": "^3.2.0" ==> "vconsole": "^3.3.4"
升级最新版本好像已经解决这个问题
