### ISSUE TITLE
引入vConsole后在vue文件中的vue方法内不生效

### ISSUE THREAD

**Issue by happyWilliam** [Tencent/vConsole#202]
引入vConsole后在vue文件中的vue方法内不生效.
以下代码Hello world1111可以打印出来，Hello world2222打印不出来

var vConsole = new VConsole();
console.log('submit...');
console.log('Hello world1111');
export default {
  created() {
    this.console.log('submit...');
    this.console.log('Hello world2222');
  },
  ........

**Comment by Maizify** [comment]
不需要用 `this.console.log` 吧，直接 `console.log` 就行了。

**Comment by zxy16621195304** [comment]
你vue事例上挂了console了?
