### ISSUE TITLE
VConsoleDefaultTab.mockConsole功能不符合预期。

### ISSUE THREAD

**Issue by mib008** [Tencent/vConsole#204]
VConsoleDefaultTab line 205:
>     if (tool.isFunction(window.onerror)) {
>       this.windowOnError = window.onerror;
>     }

这句保留既定义window.onerror的操作，其this.windowOnError会在constructor的
line 27: 
> this.windowOnError = null; 

中被设置为null，从而导致既定义的window.onerror失效。

**Comment by Maizify** [comment]
已合并了PR。
