### ISSUE TITLE
输入框无法粘贴文字

### ISSUE THREAD

**Issue by iShawnWang** [Tencent/vConsole#206]
![](https://ws2.sinaimg.cn/large/006tNbRwgy1fwbcfqm08kj30hs0vkabt.jpg)

已知 iPhone6 iPhone X 和 荣耀 10, 小米 8 都复现过改问题

长按 `command` 位置, 无法粘贴文字

**Comment by Maizify** [comment]
这个输入框理应是不出现在小程序内的，自然也不能粘贴，这里可能是小游戏侧的问题。请先不要使用这个输入框。

**Comment by iShawnWang** [comment]
! 这样么... 这个 command 输入框确实很有用啊... 一直都在用, 可以直接 调用`wx.showModel()` 等方法
是内置的功能, 不应该是小游戏专用的 !!!
~~怀疑是不是原生的 View 如 canvas 等覆盖了这个组件 ?~~
