### ISSUE TITLE
请求接口使用fetch 时, 看不到请求的记录

### ISSUE THREAD

**Issue by liaocaiming** [Tencent/vConsole#207]
请求接口使用fetch 时, 在NetWork上看不到网络接口的请记录, 是不支持fetch么

**Comment by sunwanxin213** [comment]
同问，请求支持fetch

**Comment by Sagittarius** [comment]
请求支持fetch。。。

**Comment by raoenhui** [comment]
请求支持fetch

**Comment by mvpmvp25** [comment]
请求支持fetch

**Comment by Sogrey** [comment]
请求支持fetch

**Comment by Maizify** [comment]
> 请求支持fetch

@Sogrey 最新版本3.4.0已经支持了的。

**Comment by Sogrey** [comment]
> > 请求支持fetch
> 
> @Sogrey 最新版本3.4.0已经支持了的。

我用的 3.0.0，， 更新 3.4.0 可以看到了 ，👍
