### ISSUE TITLE
我们针对vConsole改写了一下，集成了更多功能，做成了Vue插件

### ISSUE THREAD

**Issue by wenghaoping** [Tencent/vConsole#215]
虽然是vue插件，但是核心代码是基于es6重写的，所以如果要改成其他的代码，只需要写一下view层接受下数据就好了。不过还是提供了很好的参考价值。
我们多的功能
1：服务器切换，业务使用
2：页面切换，vue中针对APP路由的切换，以及记录等
3：抓包，多了筛选功能，
4：console，一样了，这个没什么可以加的了，
5：本地存储的增删改查。
6：美化了UI，还特意找了产品和UI，来设计一下，哈哈哈哈哈

http://m.prepub.tangeche.com/
我们预发环境的，仅供参考，

**Comment by Maizify** [comment]
在哪可以体验呢？

**Comment by pangjunpeng** [comment]
![image](https://user-images.githubusercontent.com/27885402/51368136-f257e880-1b28-11e9-979f-dbc548ad4cae.png)

**Comment by libin1991** [comment]
很想看下Vue版本的

**Comment by wenghaoping** [comment]
http://m.prepub.tangeche.com/
我们预发环境的，仅供参考，

**Comment by wenghaoping** [comment]
> 很想看下Vue版本的

http://m.prepub.tangeche.com/
我们预发环境的，仅供参考，

**Comment by libin1991** [comment]
开源了吗？感觉UI挺清爽的

**Comment by libin1991** [comment]
> > 很想看下Vue版本的
> 
> http://m.prepub.tangeche.com/
> 我们预发环境的，仅供参考，

**开源了吗？感觉UI挺清爽的**
