### ISSUE TITLE
为何要重写window.JSON.stringify？有人提了这个问题但是被关了

### ISSUE THREAD

**Issue by kangkang07** [Tencent/vConsole#223]
lib/tool.js  第165行
另外
https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js
这个脚本里貌似是把这个重写去掉了，但是从这几天开始随机的会出现包含重写的代码。
麻烦检查一下

**Comment by Maizify** [comment]
JSON 是 3.2.0 版本的 PR 导致的 bug，下一个版本将修复。
楼顶的 URL 是 3.0.0 版本的，因此不受影响。这个地址的 vConsole 是否有人更新，我得再去确认一下。

**Comment by kangkang07** [comment]
![image](https://user-images.githubusercontent.com/3735487/51083071-76d3f100-174e-11e9-9a1a-5c53f6b462ac.png)
偶尔会拉到3.2的版本

**Comment by sola614** [comment]
坑爹，url是3.0.0，结果是3.2.0的，导致用了JSON.stringify()方法的请求全都出错

**Comment by littlepoolshark** [comment]
坑爹啊，导致我线上JSON.stringify()的返回值都是[object object]!!!!

**Comment by littlepoolshark** [comment]
@Maizify ,我引用的链接是：https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js。一样报错的！

**Comment by Maizify** [comment]
实在抱歉，上周有同事将 3.0.0 版的 CDN 文件换成了 3.2.0 版本，恰好 3.2.0 又有 JSON bug，引起上述问题。
现在已经回退，3.0.0 的 CDN 路径应该不会再拉到 3.2.0 版本了。（已拉到的，可能会有 CDN 缓存，我们稍后会清一次缓存，急的话可通过在 URL 后加任意参数来刷新缓存。）
3.2.0 的 JSON 问题，会在稍后的版本中修复。

**Comment by SnowZhangXl** [comment]
![image](https://user-images.githubusercontent.com/30932683/51095632-19dd4700-17f1-11e9-9810-6f90a5cbcc91.png)
![image](https://user-images.githubusercontent.com/30932683/51095649-42fdd780-17f1-11e9-86c6-01efc1b25b53.png)

**Comment by SnowZhangXl** [comment]
好像也没判断请求数据是不是为空。

**Comment by littlepoolshark** [comment]
作为一个第三方库，对全局的原生方法应该秉持着一个谨慎处理的态度。这种细节虽小，但是才是体现开发者专业素养的地方。如果你想覆盖原生方法，你可以用个立即执行函数包着，自己类库内部消费，怎么都行。你这么不小心就让它泄漏出去，污染了全局，有没有想过会对众多开发者带来大量的问题定位成本呢？还有把CDN文件替换一事，这种犯错未免也太低级了吧？我也算是爱之深责之切，希望作为开源作品，还是能够秉承认真负责的态度为好。

**Comment by Maizify** [comment]
上次的 code review 确实没有做到位，导致合并了一个欠妥的改动。
另一方面，这个 CDN 文件原本是公司对内使用的，后来为了方便大家便公开出来。现在由于内部业务调整，有其他同事用错误的方法升级了这个文件，导致上述问题。没有将正确的升级操作同步给新同事，也是我的失误。
这次事故确实是我们做得不到位，给大家造成的困扰，实在抱歉。接下来的一周里我会尽快修复这个 bug。

**Comment by feshionxu** [comment]
怎么现在3.0.0 打开又是3.2.0了？？！

**Comment by feshionxu** [comment]
![image](https://user-images.githubusercontent.com/14904428/51101069-05f70c80-1814-11e9-8512-72453a60c959.png)

**Comment by feshionxu** [comment]
@Maizify 能解决下吗，发个稳定没有问题的版本。

**Comment by SilasDong** [comment]
浪费的我一个下午的时间，线下调式都没有问题 一打包 部署就出错 
测试JSON.parse(JSON.stringify(obj)) 居然报错 真是被坑惨了

**Comment by feshionxu** [comment]
> http://wechatfe.github.io/lib/vconsole/3.0.0/vconsole.min.js
> 3.0.0 可以用这个。

两个是一样的吗 http://wechatfe.github.io/lib/vconsole/3.0.0/vconsole.min.js这个在移动端（h5）不行 （没有显示出来）

**Comment by guiguzixl** [comment]
你们真的太过分了，这种失误，不想说垃圾，但真的垃圾

**Comment by Maizify** [comment]
刚才 CDN 缓存还没清完，现在好了，应该不会出现 3.2.0 了。

**Comment by jwnoal** [comment]
浪费了一天的时间

**Comment by firstshow** [comment]
线上bug，排查了半天，因为这个，以后不会用这个了

**Comment by wusfen** [comment]
我用这个
https://github.com/wusfen/console.js

**Comment by HarryQQ** [comment]
排查了大半天～都2020年12月22日还有缓存吗？～日了狗～
<script src="https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js" type="text/javascript"></script>

**Comment by VisionZheng** [comment]
坑啊，排查了半天才知道是这个文件影响的

**Comment by syd192** [comment]
出现同样问题 太坑，。。

**Comment by Maizify** [comment]
@HarryQQ @VisionZheng @syd192 
我们拉运维同学检查了下，确实有2台CND节点的文件是错误的，应该是上次的遗留问题。现已修复。
建议不要再使用这个CDN了（一开始只是为公众平台内部使用），尽量放到自己服务器上。

**Comment by RianMan** [comment]
被坑惨了 我靠，我tm还以为是我浏览器的问题，😂
