### ISSUE TITLE
bug:console 输出数组， 下标顺序按照首字符排序

### ISSUE THREAD

**Issue by basestart** [Tencent/vConsole#224]
环境： vivo x20 plus a
测试变量： var a = [0,1,2,3,4,5,6,7,8,9,10,11]
测试代码 ： console.log(a);
输出结果： 没有按照下标的数字顺序排序
0 0
1 1
10 10
11 11
2 2
3 3
4 4
...
预期结果：
0 0
1 1
2 2
...
10 10
11 11

**Comment by Maizify** [comment]
PR #197 已经修复这个问题了，接下来的版本会带上。
