### ISSUE TITLE
vconsole network 查看不到网络请求

### ISSUE THREAD

**Issue by zhangjichengcc** [Tencent/vConsole#226]
react项目，正常的网络请求在vconsole的network页面无任何显示，vconsole版本v.3.2.1

**Comment by Maizify** [comment]
现在只能抓住 XHR 请求，是不是用了别的方式？

**Comment by zhangjichengcc** [comment]
是正常的XHR请求，目前调试开发环境移动端项目，是vconsole需要加什么配置吗？目前在全局的global.js用import引入的，然后直接new对象
| |
张吉成
|
|
zhangjichengcc@163.com
|
签名由网易邮箱大师定制
在2019年1月17日 14:56，Maiz<notifications@github.com> 写道：

现在只能抓住 XHR 请求，是不是用了别的方式？

**Comment by Maizify** [comment]
不需要额外配置。不知道是不是 XHR 被别的地方覆盖重写了？

**Comment by zhangjichengcc** [comment]
覆盖重写是什么意思呀？在pc端调试，这些请求都可以看到。是否和引入的位置有关？在global引入会有一个sockjs-node/info的请求信息出现，其他地方引入就是空的。还有因为项目在本地调试，配置了代理，所有请求都是走的localhost，这有关系吗

**Comment by Maizify** [comment]
PC 端没问题的话证明 vConsole 应该是 OK 的。尝试在程序最后再引入看看。

**Comment by zhangjichengcc** [comment]
pc我指的是chrome浏览器的调试，vconsole的话在pc端也没有显示

**Comment by Maizify** [comment]
有没有用什么网络库？

**Comment by margin-0** [comment]
> 有没有用什么网络库？

意思是目前是不支持fetch的对么

**Comment by liufeisprit** [comment]
> 现在只能抓住 XHR 请求，是不是用了别的方式？

fetch看不到请求吗？

**Comment by smancang** [comment]
最新版本遇到了同样的问题，pc和移动network无法捕获请求

**Comment by GMCoder** [comment]
> 不需要额外配置。不知道是不是 XHR 被别的地方覆盖重写了？

@Maizify 我也遇到了这种情况，麻烦请问什么情况的覆盖重写会造成这种结果？

**Comment by Tonysmark** [comment]
fetch 请求  没有任何数据   webpack HMR 竟然能看到一些信息

**Comment by zhangjichengcc** [comment]
vconsole无法捕捉fetch的请求，但不代表没有请求

**Comment by zhaikui89** [comment]
websocket连接也捕获不到
