### ISSUE TITLE
请问有计划开发Network捕获到fetch请求吗？

### ISSUE THREAD

**Issue by mvpmvp25** [Tencent/vConsole#229]
请问有计划开发Network捕获到fetch请求吗？

**Comment by freemember007** [comment]
我们直接引用腾讯官方的链接地址，问题持续一周多了，这实在是有史以来预到的最离谱的一问题（从来没有哪个问题3天内找不到原因的），现在终于找到原因，但也无能为办，只能干等。
现在想了解：这个地址对应服务器缓存策略是多久失效？
```html
<!-- 微信vconsole -->
    <script type="text/javascript" src="https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js"></script>
```

**Comment by Maizify** [comment]
> 请问有计划开发Network捕获到fetch请求吗？

有的，不过得等一等。

**Comment by freemember007** [comment]
所有的post请求提交的json数据格式都不对，导致程序出错。不过，现在好了。谢谢！

**Comment by tianyk** [comment]
建议直接用 [Eruda](https://github.com/liriliri/eruda)

**Comment by Sogrey** [comment]
> > 我们直接引用腾讯官方的链接地址，问题持续一周多了，这实在是有史以来预到的最离谱的一问题（从来没有哪个问题3天内找不到原因的），现在终于找到原因，但也无能为办，只能干等。
> > 现在想了解：这个地址对应服务器缓存策略是多久失效？
> > ```
> > 
> >     <script type="text/javascript" src="https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js"></script>
> > ```
> 
> CDN 已经清理过缓存了，现在已经是正确的 3.0.0 版本了。你们现在遇到了什么问题呢？

测试已支持
