### ISSUE TITLE
use vConsole in Nuxt.js

### ISSUE THREAD

**Issue by fyeeme** [Tencent/vConsole#232]
I found not document about how to use vconsole in nuxt.js, so I write this for anyone who need it.

 1. create vconsole.js in folder plugins
```html
plugins
    vconsole.js
```

2. open vconsole.js ,put belowing code 

```js
const Vconsole =
  process.env.NODE_ENV !== 'production' ? require('vconsole') : {}

export default ({ app }, inject) => {
  if (process.env.NODE_ENV !== 'production') inject('vConsole', new Vconsole())
}
```

3.  use vconsole.js

add the file path inside the plugins key of our nuxt.config.js:

```js
  plugins: [
    { src: '~/plugins/vconsole.js', ssr: false }
  ],
```

Okey ,now you can use vconsole in nuxt.js

**Comment by yoruponder** [comment]
I use it in nuxtConfig.head.script.
`
let vconsole = { hid: 'vconsole', src: 'your vconsole.min.js path' };
if( env ==  'production' ) {
}
`

**Comment by yoruponder** [comment]
I define it in nuxtConfig.head.script.
```javascript
nuxt.config.js

let vconsole = { hid: 'vconsole', src: 'your vconsole.min.js path' };

if( env ==  'production' ) {
  vconsole = '';
}

nuxtConfig = {
  head: {
    script: [
      vconsole
    ]
 }
}

````
Init vconsole in entry file

```javascript
if(process.browser){
  if (config.env != 'production' && window.VConsole){
    window.vConsole = new VConsole();
  }
}
```

**Comment by geminiyellow** [comment]
please make a PR for this.
