### ISSUE TITLE
3.2.0版本，为什么new之后，不会出现在dom上呢

### ISSUE THREAD

**Issue by cuijianjun** [Tencent/vConsole#236]
#### on document ready后 let vConsole = new VConsole(); 为什么页面不显示呢，求助

**Comment by luck2011** [comment]
+1

**Comment by libin1991** [comment]
如果是用webpack之类的，可以用 https://github.com/libin1991/Mobile-webpackPlugin-for-consoleDebug ，这样是打包进去，就不会出现外联问题
