### ISSUE TITLE
能否针对iPhoneX系列优化一下？

### ISSUE THREAD

**Issue by fula2013** [Tencent/vConsole#241]
vConsole的初始入口按钮，以及唤出后的控制台都贴近页面底部，但是iPhoneX系列（或者其它有相似问题的安卓全面屏）页面底部是系统触控敏感区（不可点击或者容易误触退回桌面），能否给底部留出空间？

**Comment by dingyi1993** [comment]
> vConsole的初始入口按钮，以及唤出后的控制台都贴近页面底部，但是iPhoneX系列（或者其它有相似问题的安卓全面屏）页面底部是系统触控敏感区（不可点击或者容易误触退回桌面），能否给底部留出空间？

最新版本的vConsole应该有适配弹窗的底部安全区，按钮初始位置可以考虑再提一个pr上去。

**Comment by Maizify** [comment]
有适配底部的安全区。其他全面屏的还有待测试……

**Comment by littlee** [comment]
可以做成初始化的时候接收位置参数吗？

**Comment by 643104191** [comment]
> 有适配底部的安全区。其他全面屏的还有待测试……

一加7pro全面屏小程序端webview使用vconsole时
默认在左下角
屏幕下侧为手势区域
导致vconsole失效

**Comment by littlee** [comment]
被迫用了最骚的初始化方式
```js
localStorage.setItem('vConsole_switch_y', window.innerHeight / 2 + '');
new VConsole();
```
这样就会一开始就在屏幕中间了
https://github.com/littlee/code_note/issues/40
