### ISSUE TITLE
不支持控制台样式 

### ISSUE THREAD

**Issue by yucccc** [Tencent/vConsole#243]
没办法在控制台自定义样式 
console.log("%cMy stylish message", "color: red; font-style: italic");

**Comment by Maizify** [comment]
会在下一版支持哈。

**Comment by yucccc** [comment]
那太棒了 大概是在什么时候下一版 微信小程序内置的vconsole也是同步更新支持吗

**Comment by k8w** [comment]
同问 这个支持有时间表吗

**Comment by LuckyHH** [comment]
同问

**Comment by FrankFan** [comment]
2020 年 几年支持了吗？

**Comment by everlose** [comment]
..快要进入2021年了，还没有支持这个哦

**Comment by Eleven-Ding** [comment]
同样的问题

**Comment by QinZhen001** [comment]
2024年 好像还是没支持
