### ISSUE TITLE
想请问下，小程序自带的vconsole看不到网络请求怎么办

### ISSUE THREAD

**Issue by Zappa451** [Tencent/vConsole#250]
需要集成这个工具包吗……没有network调试网络请求真的好不方便

**Comment by Maizify** [comment]
目前确实看不到，因为小程序内的并不是普通的 XHR 请求。这个功能有待后续支持。

**Comment by easonjim** [comment]
请问这个功能还会支持吗？小程序迫切需要啊！@Maizify

**Comment by SeanBurt** [comment]
现在小程序可以看到network了吗？
