### ISSUE TITLE
Warnings while compiling.

### ISSUE THREAD

**Issue by oimmc** [Tencent/vConsole#259]
./node_modules/_vconsole@3.3.1@vconsole/dist/vconsole.min.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'data:application/json;charset=utf-8;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(a))))+"': Error: Can't resolve './data:application/json;charset=utf-8;base64,"+btoa(unescape(encodeURIComponent(JSON.stringify(a))))+"'.......

**Comment by Maizify** [comment]
请问是什么项目的编译？

**Comment by wangyajundev** [comment]
> 请问是什么项目的编译？

webpack react

**Comment by Maizify** [comment]
尝试下关掉Source Map（比如 Source-Map-Loader）？我看到这段报错代码在最近历史版本里都存在，可能不是近期版本引起的。不知是不是 Source Map 工具误识别了。
