### ISSUE TITLE
vue项目引入vconsole，打包报错

### ISSUE THREAD

**Issue by yanjing1109** [Tencent/vConsole#260]
引入方式
import VConsole from 'vconsole'
new VConsole()

![image](https://user-images.githubusercontent.com/12757535/60484686-fdfd2d00-9ccc-11e9-879c-490d3c63da7a.png)

打包后
![image](https://user-images.githubusercontent.com/12757535/60484738-271dbd80-9ccd-11e9-933f-cbc69b400959.png)

**Comment by Maizify** [comment]
请问 v3.3.0 由此问题吗？

**Comment by EthanZhong** [comment]
和你一样的问题，vue项目开发过程中vconsole正常，一旦webpack打包发布上线，就报这个错误。

**Comment by Maizify** [comment]
我这边使用 webpack 打包 vue + vConsole 未能重现。可否贴一下 webpack.config.js 或其他相关代码片段？

**Comment by lc-01010** [comment]
版本回退到3.3.0解决此问题

**Comment by EthanZhong** [comment]
> 
> 
> 我这边使用 webpack 打包 vue + vConsole 未能重现。可否贴一下 webpack.config.js 或其他相关代码片段？

测试了一下发现开启webpack UglifyJsPlugin插件后导致的

**Comment by ychongsaytc** [comment]
webpack 使用 mishoo/UglifyJS2 压缩 JS 的 `compress` 配置中加入 `inline: 2` 即可避开 vConsole 的这个 bug。

**Comment by JasonMgz0411** [comment]
@ychongsaytc Hello，你好，晓得具体原因是什么么，解决办法你说的这个是可行的

**Comment by yanjing1109** [comment]
暂时没找到其他方案，目前是将vconsole放在html中引入，可以避免打包错误的问题
