### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by gitdust** [Tencent/vConsole#262]
vue 项目，生产环境引入报错：

`Super expression must either be null or a function`

```js
import VConsole from 'vconsole';
new VConsole();
```
cdn 引入就可以

**Comment by Maizify** [comment]
请问是多少版本的vConsole？

**Comment by hhgnsc** [comment]
@gitdust 这是UglifyJS的问题，你webpack压缩设置`inline:false`就好了，像这样：
```javascript
new UglifyjsWebpackPlugin({
  uglifyOptions: {
    compress: {
      inline: false
    }
  }
})
```

**Comment by gitdust** [comment]
@Maizify 已解决；
@hhgnsc 感谢；

**Comment by wkl007** [comment]
感谢大佬，解决问题

**Comment by JasonMgz0411** [comment]
@wkl007 Hello，你好，晓得具体原因是什么么，解决办法上面的方案是可行的

**Comment by hhgnsc** [comment]
> @wkl007 Hello，你好，晓得具体原因是什么么，解决办法上面的方案是可行的

Uglifyjs开启inline模式时，压缩算法有问题。不是vconsole的问题，其他插件只要压缩了也有可能出这个错。
