### ISSUE TITLE
现在使用vconsole调试出现俩问题，一个是拖动会报错，还有就是会出现view undefined

### ISSUE THREAD

**Issue by make-dream** [Tencent/vConsole#263]
![PF8$8`J(O0}V9S1QC35K_`B](https://user-images.githubusercontent.com/20986400/60657824-8c67df00-9e84-11e9-9ec1-ee867d250997.png)
![_T5C_ D1 J9FN8252I`4N C](https://user-images.githubusercontent.com/20986400/60657879-a3a6cc80-9e84-11e9-8f50-12142022fcfb.png)
图一为拖动按钮报错
图二为切换路由报错

**Comment by Maizify** [comment]
报错可否展开，截图具体报错代码？
图二里的关键字 `view`，在 vConsole 内并不存在，建议检查下业务代码。

**Comment by make-dream** [comment]
![image](https://user-images.githubusercontent.com/20986400/60699778-f5546300-9f27-11e9-9820-2aa91f2515fa.png)
![image](https://user-images.githubusercontent.com/20986400/60699813-1452f500-9f28-11e9-8220-5a068ff4569d.png)
![image](https://user-images.githubusercontent.com/20986400/60699824-20d74d80-9f28-11e9-8cc5-16d767f0f740.png)
![image](https://user-images.githubusercontent.com/20986400/60699840-2af94c00-9f28-11e9-9ef4-a3c6ca93650a.png)
![image](https://user-images.githubusercontent.com/20986400/60699853-3e0c1c00-9f28-11e9-85ed-8c4637696550.png)
图一为拖动vconsole报错，剩下是点击路由跳转报错view
