### ISSUE TITLE
安卓APP使用vConsole显示很大,不是响应式?

### ISSUE THREAD

**Issue by yxgmagic** [Tencent/vConsole#268]
我试过多个手机都是如下效果:
![_-370015828_Screenshot_20190720_085712_io dcloud](https://user-images.githubusercontent.com/30786902/61572263-4c803900-aacd-11e9-8730-b7c84f57d4a2.jpg)
![WIFI0s0704350438Screenshot_20190720_085721_io dcl](https://user-images.githubusercontent.com/30786902/61572264-5013c000-aacd-11e9-9383-17d2f42e482a.jpg)
我用的是VUE.
@Maizify @fireyy @zswang @raphealguo @hzlzh

**Comment by Maizify** [comment]
检查下是否被页面内的其他样式影响了vConsole字体？默认是不会有这么大的。

**Comment by fancyboynet** [comment]
我的做法是写死字体大小
```
<style>
        #__vconsole{
            font-size: 14px !important;
        }
    </style>
```
