### ISSUE TITLE
错误信息显示不完整,没有针对map文件的映射

### ISSUE THREAD

**Issue by lilegang1589** [Tencent/vConsole#273]
项目开启sourcemap在通过webpack打包之后，浏览器中的错误信息和vconsole中的不一样，vconsole不能很好的定位问题所在
![QQ20190806-0](https://user-images.githubusercontent.com/31850636/62512839-41a70180-b84c-11e9-9842-76ef9fa57483.png)
![QQ20190806-1](https://user-images.githubusercontent.com/31850636/62512880-761abd80-b84c-11e9-9a67-d86b3721e69d.png)

**Comment by Maizify** [comment]
现在vConsole只会打印`window.onerror`里捕获的原始信息，如果`window.onerror`里的错误没有对sourcemap做处理，那么只会原样输出。后续可能会加入对sourcemap的支持，谢谢反馈~

**Comment by gyf30827** [comment]
现在能支持 sourcemap 了吗

**Comment by gyf30827** [comment]
@Maizify 现在能支持 sourcemap 了吗
