### ISSUE TITLE
vconsole界面显示异常

### ISSUE THREAD

**Issue by fengyang0329** [Tencent/vConsole#276]
vConsole版本3.2.2，运行环境：xcode12.1 ,异常：界面上没有任何东西，就一个hide按钮。
请问我这个是什么情况？
`var vConsole = new window.VConsole({
                                          defaultPlugins: ['system', 'network', 'element', 'storage'], // 可以在此设定要默认加载的面板
                                          maxLogNumber: 1000,
                                          // disableLogScrolling: true,
                                          onReady: function() {
                                          console.log('vConsole is ready.');
                                          },
                                          onClearLog: function() {
                                          console.log('on clearLog');
                                          }
                                          });
 console.info('欢迎使用 vConsole。vConsole 是一个由微信公众平台前端团队研发的 Web 前端开发者面板，可用于展示 console 日志，方便开发、调试。');`
![931565171408_ pic_hd](https://user-images.githubusercontent.com/9264567/62613547-39c68a80-b93c-11e9-9027-b61862b268b1.jpg)

直接调用这种初始化方式var vConsole = new VConsole();也会报错，报错信息如下图:
![379EC673-86C8-4145-813A-E108D8FA55C7](https://user-images.githubusercontent.com/9264567/62613729-9a55c780-b93c-11e9-9a80-3f2f4351dc58.png)

**Comment by Maizify** [comment]
这个看起来是因为你的页面开启了CSP，导致vConsole无法加载成功。可以考虑给vConsole的<script>加上CSP的配置。
