### ISSUE TITLE
3.3.3 采用 DOMContentLoad，在异步加载方式下不会挂载面板

### ISSUE THREAD

**Issue by Fiberlu** [Tencent/vConsole#278]
通过查看源码，发现 3.3.3 版本改用成了 DOMContentLoad 事件来挂载 VConsole 的面板（前置判断是 document.readyState == 'complete'），但这样会有一个问题，就是，当 vconsole 是通过异步 script 标签来加载或者是在 DOMContentLoad 事件之后的运行时加载的话（比如在 webpack 下用 import('vconsole') 来加载），这个时候
 document.readyState == 'complete'  为 false，而 DOMContentLoad 也已经发生了，所以就不会挂载面板

**Comment by Maizify** [comment]
收到，我处理一下。

**Comment by Maizify** [comment]
试下v3.3.4吧。构造了下你说的场景，测试通过。
