### ISSUE TITLE
disableLogScrolling选项无效

### ISSUE THREAD

**Issue by DMQ** [Tencent/vConsole#282]
disableLogScrolling选项无效，无法禁用日志面板自动滚动到底部。查看历史日志时，有新日志打印总是自动滚动到新日志

**Comment by DMQ** [comment]
补充一下，在vue项目，把 `element` tab放出来，就会导致disableLogScrolling失效

**Comment by Maizify** [comment]
这就神奇了，小于3个tab就没事吗？

**Comment by DMQ** [comment]
> 这就神奇了，小于3个tab就没事吗？

后来发现，只有log一个tab的时候才真的没事￣□￣｜｜

**Comment by songhongliang** [comment]
心跳请求 会导致一直刷新Log 中的布局
目前 我这么改的
window.vConsole = new VConsole();
vConsole.pluginList.network.scrollToBottom = function() {
        if (!this.vConsole.option.disableLogScrolling) {
               var $box = vConsole.$.one('.vc-content');
              $box.scrollTop = $box.scrollHeight - $box.offsetHeight;
        }
}
 vConsole.setOption({disableLogScrolling: true});
