### ISSUE TITLE
network里无法监听页面加载时的ajax请求，

### ISSUE THREAD

**Issue by MissMin** [Tencent/vConsole#284]
RT.   network里无法捕捉页面加载时的ajax请求，但是绑在事件里的ajax请求可以捕捉到，，请问怎么解决

**Comment by Maizify** [comment]
加载完vConsole之前的Ajax，是捕获不到的。楼主的情况应该是这样的吧？

**Comment by MissMin** [comment]
搞清楚了是引入顺序的问题，要在请求代码之前引入并初始化vConsole。
