### ISSUE TITLE
"Content-Type": "multipart/form-data"类型请求vconsole只能看到response

### ISSUE THREAD

**Issue by pengfeir** [Tencent/vConsole#297]
chrome 
![image](https://user-images.githubusercontent.com/22837913/71406171-5d336d00-2672-11ea-92b0-bc6508cd47c6.png)
vconsole 
![image](https://user-images.githubusercontent.com/22837913/71406216-7b00d200-2672-11ea-93a9-8d56415729a0.png)

**Comment by Maizify** [comment]
最新3.4.0版本已经支持了，可以尝试最新版本看看。
