### ISSUE TITLE
只有一个错误码，既没有行号也没有stack trace

### ISSUE THREAD

**Issue by shanhuiyang** [Tencent/vConsole#306]
我这个页面在安卓版微信和qq浏览器上打不开，然后诉诸vConsole。
但是只拿到一个简单的script error，没有其他信息。请问各位大神这种情况我应该怎么debug？

![webwxgetmsgimg](https://user-images.githubusercontent.com/50712413/75620196-ad720280-5bc0-11ea-88ea-e3f7855feedb.jpeg)

看了一下教程好像没有相关说明。

**Comment by TheWindRises-2** [comment]
https://github.com/TheWindRises-2/VConsole.art2

**Comment by shanhuiyang** [comment]
> https://github.com/TheWindRises-2/VConsole.art2

Thanks! Let me try.
