### ISSUE TITLE
chrome 有个警报

### ISSUE THREAD

**Issue by cuiqg** [Tencent/vConsole#319]
```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
```
chrome: 81.0.4044.138

**Comment by scplay** [comment]
+1

**Comment by Maizify** [comment]
这个不影响的，可以忽略。

**Comment by mehdijalaly** [comment]
> ```
> 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
> ```
> 
> chrome: 81.0.4044.138
