### ISSUE TITLE
我在vConsole原有的基础上添加了日志打印位置

### ISSUE THREAD

**Issue by TheWindRises-2** [Tencent/vConsole#320]
日志打印与报错的行列号都可以捕捉到
https://github.com/TheWindRises-2/VConsole.art2

**Comment by HappyLeiLei** [comment]
强烈建议支持输出打印位置，同步调试的时候无法定位输出位置，对排查日志位置很麻烦。

**Comment by Maizify** [comment]
感谢提供建议~
