### ISSUE TITLE
vConsole会受到全局样式影响而看不清文字

### ISSUE THREAD

**Issue by Dreagonmon** [Tencent/vConsole#323]
在定义了全局样式的时候，vConsole中的文字会受到样式影响，从而看不清文字。

比如我想做一个全局主题为黑色的页面：

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="js/vconsole.min.js"></script>
  <script>
    var vConsole = new VConsole();
    console.log("Hello Tencent!");
    console.log("Hello Console!");
  </script>
  <title>Test</title>
  <style>
    body {
      background-color: black;
    }
    p, h1, h2, div {
      color: white;
    }

    hr {
      background-color: white;
    }
  </style>
</head>
<body class="black">
  <p>Hello Dragon</p>
</body>
</html>
```

实际运行效果是这样子的：

![TIM图片20200611100959](https://user-images.githubusercontent.com/16630430/84337311-d183ad80-abcb-11ea-821f-052fc218093c.png)

文字变成了白色，没有办法阅读。

当然这里可以通过限制style的作用域来解决，可是要是项目里面用到的某些库修改了全局的样式，就会非常难受了

**Comment by Maizify** [comment]
尝试了下，不太好搞，目前的结论是支持不到。
vConsole内有用到大量CSS继承样式，比如子div会用到父div的字色。若外部直接写了最顶层div样式 `div { color:white }`，那么肯定会影响到vConsole内部。除非内部每个容器都写了精确的样式，不然还是会被覆盖。
另一个思路可能是试用web component，但是代价就太大了。
