### ISSUE TITLE
touch相关的事件捕获的对象属性不全

### ISSUE THREAD

**Issue by ougege** [Tencent/vConsole#327]
如下图所示，在移动端调试时，touch的event属性只有一项，其他不见了
![深度截图_选择区域_20200617155305](https://user-images.githubusercontent.com/18638822/84871152-bf65ab80-b0b2-11ea-9347-9e6a13a3aa90.png)

**Comment by callmezhenzhen** [comment]
我也遇到这种问题了，请问有解决方案吗

**Comment by callmezhenzhen** [comment]
vconsole内部应该会先JSON.stringify，这样就会导致这个问题

**Comment by Maizify** [comment]
先前只会显示出 `Object.getOwnPropertyNames()` 内的属性，因此对于 `TouchEvent` 只有 `isTrusted` 属性。
现在已更改。
