### ISSUE TITLE
本地引入  VConsole 时 报了这个错

### ISSUE THREAD

**Issue by Marszht** [Tencent/vConsole#333]
![image](https://user-images.githubusercontent.com/38552120/90704390-f62e8c80-e2c2-11ea-83f3-a95b723f3814.png)

vconsole版本：v3.3.4
node: v10.18.0

**Comment by 13737240701** [comment]
我也遇到了这个问题

**Comment by littlee** [comment]
路径写错了

**Comment by Marszht** [comment]
> 我也遇到了这个问题

项目从新打包一下，应该就可以了
