### ISSUE TITLE
支持 console.dir()？

### ISSUE THREAD

**Issue by M69W** [Tencent/vConsole#334]
目前使用 [版本3.3.4](https://github.com/Tencent/vConsole/releases/tag/v3.3.4)
该版本无法显示console.dir()
某些情况下，需要打印 对象的所有属性和方法。

请问后期会支持 console.dir() 吗？

**Comment by M69W** [comment]
经过测试，
[版本v3.14.6](https://github.com/Tencent/vConsole/releases/tag/v3.14.6) 还未支持 console.dir()

**Comment by M69W** [comment]
Wontfix？

**Comment by Maizify** [comment]
`console.dir` 是树形展示一个 object，同样的功能 `console.log` 也可以实现。楼主的意思是希望在调用 `console.dir()` 时 vConsole 内也会有输出？
