### ISSUE TITLE
无法将日志输出到自定义插件中

### ISSUE THREAD

**Issue by xxhanjiexx** [Tencent/vConsole#337]
var vConsole = new VConsole();
    console.log('Hello world');
    var myPlugin = new VConsole.VConsolePlugin('myplugin', 'My Plugin');
    myPlugin.on('renderTab', function(callback) {
        var html = '\<div>Click the tool button below!\</div>';
	    callback(html);
    });
 
    vConsole.addPlugin(myPlugin);
    console.info('[myplugin]', 'bar');
    console.info('[system]', 'bar');

**Comment by Maizify** [comment]
要将插件继承 `VConsoleLogPlugin` 类，才可以享有日志功能。普通的插件，视图需要自己画，一般用来承载开发者自定义功能。
