### ISSUE TITLE
移动端支持长按复制吗？

### ISSUE THREAD

**Issue by jijiqw** [Tencent/vConsole#344]
https://cdn.bootcdn.net/ajax/libs/vConsole/3.3.4/vconsole.min.js    我们用的是这个版本， 一些token  cookie  想复制出来调试， 但是这个版本的长按没有反应。 想问下这个项目目前支持了长按复制不

**Comment by Maizify** [comment]
```
-webkit-user-select: auto
```
vConsole的CSS里有加这句，所以理论上是支持长按复制的。现在是哪些地方不行呢？

**Comment by sunlanda** [comment]
https://github.com/sunlanda/vconsole-outputlog-plugin 写了个日志复制插件 欢迎试用~  😆

**Comment by Maizify** [comment]
3.5.0将支持单log复制。也可以使用上面sunlanda的插件哈。
