### ISSUE TITLE
微信能打开 但是Network没有捕获到请求

### ISSUE THREAD

**Issue by 502647092** [Tencent/vConsole#346]

**Comment by Maizify** [comment]
请问是用什么方式发的请求？

**Comment by 502647092** [comment]
@Maizify 
fetch请求的
https://pay.yumc.pw/h5/pay.html?id=20201227090000511005787014
这个是地址 你可以看下

**Comment by Maizify** [comment]
3.3.4版本不支持fetch请求。
目前开发中的最新版本会支持fetch，可以等待一下。

**Comment by 502647092** [comment]
好的

**Comment by Maizify** [comment]
3.4.0已经支持了。
