### ISSUE TITLE
Uncaught SyntaxError: The requested module '/@modules/vconsole/dist/vconsole.min.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by zhayes** [Tencent/vConsole#350]
Uncaught SyntaxError: The requested module '/@modules/vconsole/dist/vconsole.min.js' does not provide an export named 'default'

![image](https://user-images.githubusercontent.com/17758062/102158985-8ec5c980-3ebd-11eb-9c81-a8818211489b.png)

**Comment by Maizify** [comment]
你的JS文件里是如何import的呢？方便贴一下代码片段吗？

**Comment by zhayes** [comment]
@Maizify  就是正常式例里面的引用。然后我觉得跟vite 有关。他们用到nodejs

**Comment by Maizify** [comment]
```
export default VConsole;
```
vconsole.js里是这样导出的，所以`default`应该是有的。
不知vite对import写法做了怎样的转义。

**Comment by zhayes** [comment]
> ```
> export default VConsole;
> ```
> 
> vconsole.js里是这样导出的，所以`default`应该是有的。
> 不知vite对import写法做了怎样的转义。

是的。我发现我用其他三方库的时候，有的也会有这个问题，比如：Eruda。暂时我就干脆不用import了，用script直接插资源地址先解决这个问题。
