### ISSUE TITLE
Vue3 项目下使用vconsole经常报内存溢出，要么就是数据绑定会出现问题

### ISSUE THREAD

**Issue by AlwaysLoveme** [Tencent/vConsole#351]
开启vconsole调试，在vue3项目会有各种报错，页面刷新错误就没有，最多的是报内存溢出，就很简单 的一个input v-model，有时就会报内存溢出，把vconsole注释掉就恢复正常。用Eruda就不会有这些问题

**Comment by Maizify** [comment]
请问是哪个版本的vConsole？

**Comment by AlwaysLoveme** [comment]
> 请问是哪个版本的vConsole？

最新版本的

**Comment by Maizify** [comment]
是否方便贴一下相关代码、报错日志？

**Comment by alleluya-young** [comment]
我也遇到这个问题 请问最后解决了吗?

**Comment by 15074769525** [comment]
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Array.slice (<anonymous>)
    at formatProps (runtime-core.esm-bundler.js?5c40:88)
    at formatTraceEntry (runtime-core.esm-bundler.js?5c40:81)
    at eval (runtime-core.esm-bundler.js?5c40:71)
    at Array.forEach (<anonymous>)
    at formatTrace (runtime-core.esm-bundler.js?5c40:70)
    at warn (runtime-core.esm-bundler.js?5c40:36)
    at Object.get (runtime-core.esm-bundler.js?5c40:6246)
    at Proxy.toString (<anonymous>)
    at Object.u [as isFunction] (vconsole.min.js?v=3.2.0:10)

**Comment by 15074769525** [comment]
也是vue3使用vconsole

**Comment by AlwaysLoveme** [comment]
> 我也遇到这个问题 请问最后解决了吗?

换成Eruda了

**Comment by Maizify** [comment]
有无可以重现的代码片段呢？我这边构造来试一下。

**Comment by Aaronlamz** [comment]
遇到同样的问题

**Comment by Hawods** [comment]
遇到同样的问题。

引用vconsole之后的报错：
`vconsole.min.js:10 Uncaught RangeError: Maximum call stack size exceeded
    at E (vconsole.min.js:10)
    at Module._ (vconsole.min.js:10)
    at VConsoleDefaultTab.f2.printLog (vconsole.min.js:10)
    at console.window.console.<computed> (vconsole.min.js:10)
    at o2.f2.printOriginLog (vconsole.min.js:10)
    at o2.f2.printLog (vconsole.min.js:10)
    at console.window.console.<computed> [as warn] (vconsole.min.js:10)
    at warn (runtime-core.esm-bundler.js:38)
    at Object.PublicInstanceProxyHandlers.ownKeys (runtime-core.esm-bundler.js:6893)
    at E (vconsole.min.js:10)`

去掉vconsole之后的报错：
`[Vue warn]: Unhandled error during execution of component event handler 
  at <AButton onClick=fn<bound onReset> > 
  at <ASpace class="button-group" > 
  at <ACol span=24 class="ant-form-item-control" > 
  at <Anonymous wrapperCol= {span: 24} hasFeedback=false colon=undefined  ... > 
  at <ARow class="ant-form-item" key="row" > 
  at <AFormItem wrapper-col= {span: 24} > 
  at <ACol span=24 > 
  at <ARow gutter=8 > 
  at <AForm ref="searchForm" label-col= {span: 8} wrapper-col= {span: 16}  ... > 
  at <BaseDataListLayout class="container" > 
  at <TradeList onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {onSearch: ƒ, onReset: ƒ, onTableChange: ƒ, onAdd: ƒ, onView: ƒ, …} > key=0 > 
  at <RouterView> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout-content" tagName="main"  ... > 
  at <ALayoutContent class="content" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > 
  at <ALayout> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout id="main" > 
  at <Main onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {onChangePassword: ƒ, onLogout: ƒ, …} > > 
  at <RouterView> 
  at <ALocaleProvider locale= {locale: "en", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider locale= {locale: "en", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} > 
  at <App>
warn @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:211
handleError @ runtime-core.esm-bundler.js:203
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:163
emit @ runtime-core.esm-bundler.js:991
handleClick @ button.js:136
callWithErrorHandling @ runtime-core.esm-bundler.js:154
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:163
invoker @ runtime-dom.esm-bundler.js:336
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of native event handler 
  at <Wave ref="wave" > 
  at <AButton onClick=fn<bound onReset> > 
  at <ASpace class="button-group" > 
  at <ACol span=24 class="ant-form-item-control" > 
  at <Anonymous wrapperCol= {span: 24} hasFeedback=false colon=undefined  ... > 
  at <ARow class="ant-form-item" key="row" > 
  at <AFormItem wrapper-col= {span: 24} > 
  at <ACol span=24 > 
  at <ARow gutter=8 > 
  at <AForm ref="searchForm" label-col= {span: 8} wrapper-col= {span: 16}  ... > 
  at <BaseDataListLayout class="container" > 
  at <TradeList onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {onSearch: ƒ, onReset: ƒ, onTableChange: ƒ, onAdd: ƒ, onView: ƒ, …} > key=0 > 
  at <RouterView> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout-content" tagName="main"  ... > 
  at <ALayoutContent class="content" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" > 
  at <ALayout> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout id="main" > 
  at <Main onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {onChangePassword: ƒ, onLogout: ƒ, …} > > 
  at <RouterView> 
  at <ALocaleProvider locale= {locale: "en", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider locale= {locale: "en", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} > 
  at <App>
warn @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:211
handleError @ runtime-core.esm-bundler.js:203
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:163
invoker @ runtime-dom.esm-bundler.js:336
runtime-core.esm-bundler.js:217 Uncaught ReferenceError: QRCode is not defined
    at Proxy.onReset (TradeList.vue:160)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at emit (runtime-core.esm-bundler.js:991)
    at Proxy.handleClick (button.js:136)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:336)`

这个错误本身没啥，但是vconsole把错误信息吃掉了

**Comment by starlet0822** [comment]
> 同样的问题，排了好久

怎么解决的？

**Comment by baiyang2292** [comment]
> 

换成Eruda了

**Comment by alleluya-young** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by baiyang2292** [comment]
> > 的问题，排了一个好久
> 
> 怎么解决的？

换成Eruda了

**Comment by Maizify** [comment]
已定位到是Vue3 proxy带来的问题，正在解决中。

**Comment by Maizify** [comment]
可以尝试下v3.10.0版本。
