### ISSUE TITLE
急切希望官方推出个导出日志功能

### ISSUE THREAD

**Issue by jiangguilong2000** [Tencent/vConsole#354]
导出log文本，因为现在得让异地客户录制视频或者截图，但log可能有10多页，要是有文本日志导出功能就方便了

**Comment by sunlanda** [comment]
https://github.com/sunlanda/vconsole-outputlog-plugin 写了个日志复制插件 欢迎试用~  😆

**Comment by Maizify** [comment]
> https://github.com/sunlanda/vconsole-outputlog-plugin 写了个日志复制插件 欢迎试用~ 😆

感谢贡献，我把插件链接添加到README里哈。
