### ISSUE TITLE
在用腾讯CDN时，发现缓存命中X-Cache-Lookup的报告和其他软件不一样

### ISSUE THREAD

**Issue by jiangguilong2000** [Tencent/vConsole#355]
同一个资源，同一台手机，同样的网络，vcosole里看到的是
Hit From Disktank3, Hit From Inner Cluster, Cache Miss
但用chrome或者腾讯云诊断APP却是Cache Hit，求解释下？
到底本地有没有命中呢？
vconsole里看到的
![image](https://user-images.githubusercontent.com/5009933/102781255-5567ef00-43d2-11eb-8211-a6e338776397.png)
但腾讯云诊断APP里看到的
![image](https://user-images.githubusercontent.com/5009933/102781281-63b60b00-43d2-11eb-9c7a-ca8342b0c2a4.png)

**Comment by Maizify** [comment]
这里是使用了 xhr 的 `getAllResponseHeaders()` 方法将 headers 信息取出来，并未做内容上的处理。
可以检查下是否有其他业务因素影响？
