### ISSUE TITLE
vconsole 3.0.0文件又变成3.2.0了

### ISSUE THREAD

**Issue by skua** [Tencent/vConsole#356]
之前相关问题 https://github.com/Tencent/vConsole/issues/223
目前引用 https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js
CDN会返回 vConsole v3.2.0 (https://github.com/Tencent/vConsole) 导致用了JSON.stringify()方法出错
Remote Address: 123.125.110.183:443
![image](https://user-images.githubusercontent.com/1639707/102783879-8d713100-43d6-11eb-8e50-2bbbeaa4106f.png)

**Comment by YongX** [comment]
同遇到，坑爹！

**Comment by James-Lam** [comment]
https://github.com/Tencent/vConsole/issues/223

**Comment by James-Lam** [comment]
https://github.com/Tencent/vConsole/issues/223
19年出现过的问题怎么又出现。。

**Comment by willylee007** [comment]
同遇到。老项目引用了[https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js](https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js)，只是引用，没有初始化vconsole。花了很长时间定位问题。这种资源还是放自己服务器吧，谁也说不准哪天又给你换了资源呢

**Comment by Maizify** [comment]
两个问题：
1、最新版不会重写`JSON.stringify`方法，可以放心尝试用最新版本。
2、这个所谓的“CDN”地址并不维护的了，不建议再使用。
