### ISSUE TITLE
安装依赖后项目无法启动，已经删除过所有依赖，然后重新安装

### ISSUE THREAD

**Issue by xvdayou** [Tencent/vConsole#357]
![image](https://user-images.githubusercontent.com/25738893/102838810-09e92b80-443a-11eb-8e84-0d7ebdf9ad22.png)

**Comment by xvdayou** [comment]
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @2.1.0 serve: `vue-cli-service serve --open`
22 error Exit status 1
23 error Failed at the @2.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Maizify** [comment]
看报错，好像没有与vConsole有关的日志？

**Comment by fantuandai** [comment]
![image](https://user-images.githubusercontent.com/35990107/104905526-76b20000-59bd-11eb-8ddd-c2a4c981854a.png)
这个babel整死我了........请问怎么解决

**Comment by fantuandai** [comment]
{
                test: /\.js$/, // Check for all js files
                exclude: /node_modules\/(?!(xxxxxxxxxxx)\/).*/,
                loader: 'babel-loader'
            },
我把webpack的这个配置去掉就行了，这是为啥
