### ISSUE TITLE
vconsole 重写 json.stringify 方法 导致格式异常的问题

### ISSUE THREAD

**Issue by codeSww** [Tencent/vConsole#358]
引入vconsole之后，JSON.stringify方法被重写，stringfiy之后的字符串格式会变化（多加逗号和回车符号）

举例：
let obj = {a:'234'}
json.stringify(a) //“{'a':'123',}”
导致无法stringify后无法parser

希望尽快修复

**Comment by xyfgh** [comment]
{a:1,b:{c:{d:2}}}会变成{a:1,b:[object Object]}，影响很严重

**Comment by Maizify** [comment]
最新版并没有重写`JSON.stringify`方法哦。看看你用的是哪个版本？

**Comment by xyfgh** [comment]
用的是//res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js

**Comment by xyfgh** [comment]
用的是//res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js
不过刚才清缓存刷新后没有问题了，之前是JSON有错的

**Comment by Maizify** [comment]
之前版本的JSON是有问题的，现在最新版本是没问题的了。
另外这个URL已经不维护的了，后面尽量不要再使用了。

**Comment by cqtangsong** [comment]
我现在也出现这个问题 window.JSON.stringify=b   导致  JSON.stringify 方法被覆盖   登录出现问题

**Comment by cqtangsong** [comment]
//res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js    这个url里面又对 json.stringify  方法重写了 现在哪一个url 是可用的呢

**Comment by Maizify** [comment]
> //res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js 这个url里面又对 json.stringify 方法重写了 现在哪一个url 是可用的呢

微信已不提供vConsole的CDN网址，可以考虑自己托管或者看下第三方托管服务。

**Comment by cqtangsong** [comment]
哦哦 那直接npm安装 vconsole   是可以用的 是么？

**Comment by Maizify** [comment]
> 哦哦 那直接npm安装 vconsole 是可以用的 是么？

可以的。

**Comment by cqtangsong** [comment]
好的 感谢🙏
