### ISSUE TITLE
vConsole 的 CDN 资源会改写全局 JSON.stringify()

### ISSUE THREAD

**Issue by Hsuer** [Tencent/vConsole#359]
![image](https://user-images.githubusercontent.com/8482405/103504131-79770600-4e91-11eb-8b05-8bac47ac2127.png)

复现页面：https://row4x.csb.app/

使用 res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/3.0.0/vconsole.min.js 这个 CDN 地址会改写全局的 JSON 序列化，导致相关依赖出错

**Comment by Maizify** [comment]
旧版本的JSON是有问题的，请尝试用最新版本的vConsole。另外这个CDN已经不维护了，尽快迁移到自己的服务器吧。
