### ISSUE TITLE
低端手机兼容性问题：Invalid attempt to iterate non-iterable instance.

### ISSUE THREAD

**Issue by YaoJiexianyuan** [Tencent/vConsole#361]
升级到3.4.0版本后，低端机报错，降到3.3.4之后恢复。
<img width="577" alt="rBAoL2AFciSABJTtAAOQTIkwjBU285" src="https://user-images.githubusercontent.com/37261541/104916631-4d00d500-59cd-11eb-810f-fcc20e50599e.png">

**Comment by Maizify** [comment]
看起来是不支持symbol的系统。原本打算不再支持低端手机了，因此这一版删掉了polyfill。
方便说下是什么牌子、型号的手机吗？我评估一下要兼容到什么程度。

**Comment by YaoJiexianyuan** [comment]
OPPO R7Plus 
ColorOS：V2.1
Android：5.0

**Comment by AdamEleven** [comment]
> 看起来是不支持symbol的系统。原本打算不再支持低端手机了，因此这一版删掉了polyfill。
> 方便说下是什么牌子、型号的手机吗？我评估一下要兼容到什么程度。

我这里也遇到了这个问题, 
IPhone 6 Plus 
IOS 10.3

**Comment by minetsh** [comment]
iPhone 6s，iOS 9.3.5 也报这个错

**Comment by Maizify** [comment]
重新加入Symbol polyfill，即将在3.4.1发布。现在可尝试dev分支下的版本。

**Comment by narutooturan** [comment]
3.15.0 红米k50也有同样的问题

**Comment by sillysillyc** [comment]
3.15.1 问题再次出现，回退到 3.3.4 版本正常

web 端 chrome 131.0.6778.205（正式版本） (arm64)

iPhone 13 Pro Max (18.2) 

都有问题
