### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by whynotsnow** [Tencent/vConsole#364]
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot set property 'transitionEnd' of undefined

**Comment by whynotsnow** [comment]
在运行到真机时报错

**Comment by Maizify** [comment]
准备在 3.4.1 里移除 `transitionEnd`。现在可以用 dev 分支试下，应该不会报这个错了。
