### ISSUE TITLE
ionic 5.0 项目，ionic-icon无法显示

### ISSUE THREAD

**Issue by ljt521** [Tencent/vConsole#365]
![image](https://user-images.githubusercontent.com/25889804/105965766-c7f97800-60be-11eb-8216-463d61070d41.png)
![image](https://user-images.githubusercontent.com/25889804/105965810-d6e02a80-60be-11eb-93dd-00a873a5da87.png)

**Comment by ljt521** [comment]
![Uploading image.png…]()

**Comment by Maizify** [comment]
fetch问题，即将在3.4.1修复。现在可尝试dev分支下的版本。
