### ISSUE TITLE
拖动vconsole时控制台会疯狂打印vconsole的坐标

### ISSUE THREAD

**Issue by neohan666** [Tencent/vConsole#366]
如题

**Comment by Maizify** [comment]
抱歉，是个失误，即将在3.4.1版本中修复。现在dev分支已经fix，可以尝试使用。

**Comment by neohan666** [comment]
> 抱歉，是个失误，即将在3.4.1版本中修复。现在dev分支已经fix，可以尝试使用。

好的

**Comment by pocketChao** [comment]
麻烦问下何时上3.4.1呢

**Comment by Maizify** [comment]
不好意思，4月初的时候已经发了，忘了在这提醒。可以试下哈。
