### ISSUE TITLE
移动端中network没有数据，PC手机模式却有

### ISSUE THREAD

**Issue by wangzeyu-ym1120** [Tencent/vConsole#367]
近一周开始在手机上查看时，network为empty
但是在PC Chrome中手机模式调试时，vconsole的network却是正常可以看到接口请求的

**Comment by Composur** [comment]
> 近一周开始在手机上查看时，network为empty
> 但是在PC Chrome中手机模式调试时，vconsole的network却是正常可以看到接口请求的

你是 hybrid 模式开发的吗？这样获取不到原生的请求吧

**Comment by wangzeyu-ym1120** [comment]
单纯在微信里打开，在手机浏览器里打开都是不显示接口信息的，在招行app里反而是显示的





------------------ 原始邮件 ------------------
发件人: Composure <notifications@github.com&gt;
发送时间: 2021年3月2日 16:19
收件人: Tencent/vConsole <vConsole@noreply.github.com&gt;
抄送: lovePink <276545028@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/vConsole] 移动端中network没有数据，PC手机模式却有 (#367)

**Comment by Maizify** [comment]
是相同的页面吗？可否发出来看看，方便调试。
