### ISSUE TITLE
更新3.4.0之后network内请求展开不流畅

### ISSUE THREAD

**Issue by liyongrui1001** [Tencent/vConsole#368]
有的点一次可以打开，有的点好几次可以打开，还有的根本就打不开，打开的不能关闭，不只是network，感觉整体都没有之前流畅了。已经先退回3.3.4版本了，期待后面的版本会好一点

**Comment by Maizify** [comment]
是否错觉？这里最近没有交互上的调整，只是增加了新的展示字段。方便的话可以录个视频看看。

**Comment by Maizify** [comment]
v3.5.2应该修复了此问题，可以更新试试看是否有效。
