### ISSUE TITLE
加载vconsole后会导致fetch api抛出异常

### ISSUE THREAD

**Issue by snys98** [Tencent/vConsole#369]
vconsole版本: 3.4.0
![image](https://user-images.githubusercontent.com/11873100/106577122-f1138000-6578-11eb-9def-17514c92936a.png)
![image](https://user-images.githubusercontent.com/11873100/106577247-1acca700-6579-11eb-9cf1-5b7a1c180f32.png)

**Comment by imtns** [comment]
我刚刚也报这个错，最后在页面初始化vconsole的前面
添加了  window.fet = window.fetch
然后后面把fetch替换成window.fet  就好了， 应该是新版vconsole 操作了全局fetch 替换成了未知什么方法了

**Comment by Maizify** [comment]
谢谢反馈，可试下3.4.1版本，针对这个问题做了修复。
