### ISSUE TITLE
抓取不到Network里面的请求和相应数据，用的是axios

### ISSUE THREAD

**Issue by yiuxiu** [Tencent/vConsole#370]
![image](https://user-images.githubusercontent.com/39853165/107036624-e2390180-67f4-11eb-879d-b57948226132.png)
用的是axios

**Comment by Maizify** [comment]
谢谢反馈，估计是vConsole的xhr处理被axios干扰了，我查查看。

**Comment by Maizify** [comment]
没有定位到具体的问题，不过这次重构了一把代码，试一下v3.6.1版本？

**Comment by xmenw** [comment]
我是用的是3.7.0的版本，还是获取不到Network里面的请求

**Comment by yucccc** [comment]
fetch也没有

**Comment by Maizify** [comment]
@yucccc @xmenw 请问你们引入vConsole和Axios的顺序是怎样的？以及可否贴下Axios发请求的代码片段？

**Comment by xmenw** [comment]
> @yucccc @xmenw 请问你们引入vConsole和Axios的顺序是怎样的？以及可否贴下Axios发请求的代码片段？

我们在项目入口文件一开始就引入了vConsole。我问了一下这个项目的前辈们，他们说我们在移动端就用原生的去请求而不用Axios或者fetch了。抱歉抱歉

**Comment by Maizify** [comment]
> 我们在项目入口文件一开始就引入了vConsole。我问了一下这个项目的前辈们，他们说我们在移动端就用原生的去请求而不用Axios或者fetch了。抱歉抱歉

好的，若后续仍有问题，可以贴一下代码片段。
