### ISSUE TITLE
Fetch api响应为null时报错

### ISSUE THREAD

**Issue by mousne** [Tencent/vConsole#371]
fetch api响应为null时候也会抛出异常    
umi-request有配置项做了处理    
但这边会抛一个Unexpected end of JSON input异常    
[报错位置](https://github.com/Tencent/vConsole/blob/73e194184ce4c619c5baab484dfbd2d42c2a3262/src/network/network.js#L500)

**Comment by Maizify** [comment]
感谢反馈。预计在3.5.0中修复这个问题。
