### ISSUE TITLE
vconsole 改变了数组下标显示顺序

### ISSUE THREAD

**Issue by Guest1798** [Tencent/vConsole#372]
![image](https://user-images.githubusercontent.com/22300377/109825520-dc5c0200-7c74-11eb-8211-7eb39a983a20.png)
有什么解决办法吗？

**Comment by jhxxs** [comment]
换回3.3.4或者用eruda

**Comment by Maizify** [comment]
感谢反馈，即将在下一版修复，预计是3.5.0。
