### ISSUE TITLE
[Bug Report] iPhone12 iOS 14.4 系统 System 显示Unknow

### ISSUE THREAD

**Issue by huangshuwei** [Tencent/vConsole#374]
型号：iPhone12 iOS 14.4 系统

System 显示Unknow。实际 navigator.userAgent 为：
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

这里的判断没有兼容到 14.4系统：
```
// device & system
    let ipod = ua.match(/(ipod).*\s([\d_]+)/i),
    ipad = ua.match(/(ipad).*\s([\d_]+)/i),
    iphone = ua.match(/(iphone)\sos\s([\d_]+)/i),
    android = ua.match(/(android)\s([\d\.]+)/i);
```

但是我不确定 iPad 或者 iPod 的最新操作系统 navigator.userAgent 也发生了变更。需要你们自己排查了（我没有iPod 或者 iPad 可以测试）

**Comment by Maizify** [comment]
实测iPhone12、iPad均能正确识别。你贴的UA并非iOS设备，而是Mac电脑上Safari浏览器，所以没有识别为移动设备的System，就显示了Unkown。
