### ISSUE TITLE
window.fetch 第二个参数是可选的。3.4.0版本覆盖系统window.fetch后，第二个参数变成必选，导致报错

### ISSUE THREAD

**Issue by morrain** [Tencent/vConsole#375]
let prevFetch = (input, **init**) => {
      let id = that.getUniqueID();
      that.reqList[id] = {};
      let item = that.reqList[id] || {};
      let query = [],
          url = '',
          method = 'GET',
          requestHeader = null;
      
      // handle `input` content
      if (tool.isString(input)) { // when `input` is a string
        method = init.method || 'GET';
        url = input;
        requestHeader = init.headers;
      } else { // when `input` is a `Request` object
        method = input.method || 'GET';
        url = input.url;
        requestHeader = input.headers;
      }

**Comment by liushengxian** [comment]
+1.

**Comment by luoquanquan** [comment]
+1

**Comment by Maizify** [comment]
谢谢反馈，3.4.1已经修复。
