### ISSUE TITLE
编写插件中的renderTab方法只会回调一次，那如果内容是动态变化的呢？

### ISSUE THREAD

**Issue by wenzi0github** [Tencent/vConsole#381]
编写插件中的renderTab方法只会回调一次，那如果内容是动态变化的呢？

怎么能持续更新面板中的内容呢？

相关文档： [2. 绑定插件事件](https://github.com/Tencent/vConsole/blob/dev/doc/plugin_building_a_plugin_CN.md#2-%E7%BB%91%E5%AE%9A%E6%8F%92%E4%BB%B6%E4%BA%8B%E4%BB%B6)

**Comment by Maizify** [comment]
面板中的内容由插件自行维护更新，后续的动态变化，可通过DOM操作来执行。renderTab的回调支持传入HTML或者Element。

**Comment by wenzi0github** [comment]
哦哦，放一个自己的dom，然后在这个dom里操作自己的数据和结构，是吧！

好的，谢谢啦！

**Comment by Maizify** [comment]
没错，你的理解是对的。
