### ISSUE TITLE
vue安装v3.5.0，本地dev时报错

### ISSUE THREAD

**Issue by xiesw95** [Tencent/vConsole#384]
![image](https://user-images.githubusercontent.com/74030285/116505002-4fd46580-a8ec-11eb-85c1-ddb655230e24.png)

**Comment by xiesw95** [comment]
v3.4.1是没有问题的

**Comment by Maizify** [comment]
是用什么构建？

**Comment by xiesw95** [comment]
> 是用什么构建？

yarn 1.22

**Comment by niuweili** [comment]
用npm构建，遇到了同样的问题+1
