### ISSUE TITLE
3.5.0版本-报错

### ISSUE THREAD

**Issue by ovenslove** [Tencent/vConsole#385]
按照3.5.0后移动端无法正常打开，之前的版本正常
![IMG_0887](https://user-images.githubusercontent.com/11400029/116525758-6c33ca80-a90b-11eb-83df-e1bcb299048a.PNG)

**Comment by Maizify** [comment]
谢谢反馈，有无网址可以试下？

**Comment by ovenslove** [comment]
@Maizify 生产环境不敢上这个版本，已经降回3.4.1了，还是很期待vue的那个插件的。

**Comment by xovel** [comment]
https://github.com/Tencent/vConsole/issues/387

就是这个问题，复现步骤如上。

**Comment by Maizify** [comment]
将在3.5.1版本修复。
