### ISSUE TITLE
vue + vconsole 3.5.0报错

### ISSUE THREAD

**Issue by jianyu3435** [Tencent/vConsole#386]
公众号和企业微信都是进去页面直接白屏，vconsole报错Uncaught SyntaxError: Unexpected token {

**Comment by JanuChen** [comment]
公众号和企业微信都是进去页面直接白屏，vconsole报错Uncaught SyntaxError: Unexpected token {

**Comment by JanuChen** [comment]
。

**Comment by gucovip** [comment]
+1
