### ISSUE TITLE
3.5.0 版本 包无法正常使用

### ISSUE THREAD

**Issue by xovel** [Tencent/vConsole#387]
复现方式：

直接打开一个空白的 Chrome 页面，开启移动端模式，添加一个自定义设备，将 userAgent 字符串设为

Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 NetType/WiFi env/demo

然后将 vConsole 3.5.0 的整个代码直接粘贴到 Chrome 的 Console 里面，之后再对 vConsole 进行初始化调用，new VConsole，此时会看到报以下错误：

VM597:10 Uncaught TypeError: "network" is read-only
    at <anonymous>:10:96288
    at a.value (<anonymous>:10:96326)
    at a.value (<anonymous>:10:95485)
    at a.value (<anonymous>:10:8942)
    at e.value (<anonymous>:10:49941)
    at e.value (<anonymous>:10:49616)
    at c (<anonymous>:10:44644)
    at new e (<anonymous>:10:44754)
    at <anonymous>:1:4

点开绿色 vConsole 按钮，发现只剩 Log 标签。

此问题在任何浏览器默认的 userAgent 字符串中带有 nettype/** 的都会有问题，比如本人的 iOS14 的微信内开。

**Comment by xovel** [comment]
查看 dist 目录下的 vconsole.min.js 文件，存在以下代码：

```js
var c=e.toLowerCase().match(/ nettype\/([^ ]+)/g);c&&c[0]&&(function(e){throw new TypeError('"'+e+'" is read-only')}("network"),t=[(c=c[0].split("/"))[1]]
```

格式化一下：

```js
var c = e.toLowerCase().match(/ nettype\/([^ ]+)/g);
            c && c[0] && (function (e) {
              throw new TypeError('"' + e + '" is read-only')
            }("network"), t = [(c = c[0].split("/"))[1]]
```

对应的源码应该在 `src\log\system.js`:

```js
// network type
    const network = ua.toLowerCase().match(/ nettype\/([^ ]+)/g);
    if (network && network[0]) {
      network = network[0].split('/');
      logMsg = [network[1]];
      console.info('[system]', 'Network:', logMsg.length ? logMsg.join(', ') : 'Unknown');
    }
```

推测应该是打包工具出现了问题。

**Comment by Maizify** [comment]
感谢反馈！将在3.5.1版本修复。
