### ISSUE TITLE
ios axios post http status code 0

### ISSUE THREAD

**Issue by hurbbit** [Tencent/vConsole#397]
![3f153094-063e-447a-9f62-ef133b80da5a](https://user-images.githubusercontent.com/25116468/118088106-255ccf00-b3f9-11eb-85c5-197cd5c5cd23.jpg)

我系统是IOS 13.6.1， 用的是axios 0.21.1。
偶尔会存在一些post 请求接口在vconsole里显示的code是0的情况。
当我用charles抓包时，接口返回的数据是正常的，而vconsole显示的状态却是0。

**Comment by Maizify** [comment]
请问vConsole版本是多少呢？

**Comment by hurbbit** [comment]
> 请问vConsole版本是多少呢？

vconsole 3.3.4
vconsole-webpack-plugin 1.5.2

**Comment by Maizify** [comment]
3.3.4很旧了，尝试升到目前最新的3.5.2看看。

**Comment by hurbbit** [comment]
好的，我试试看能不能解决这个问题

**Comment by hurbbit** [comment]
> 3.3.4很旧了，尝试升到目前最新的3.5.2看看。

刚刚更新了跑了下，还是不行

**Comment by Maizify** [comment]
好的，我试下axios。说不定是被axios影响了vConsole的xhr钩子。

**Comment by Maizify** [comment]
我这边重现不出来。是否方便贴一下axios的代码片段？

**Comment by Maizify** [comment]
可以试一下v3.6.1。
