### ISSUE TITLE
清空cookie逻辑问题

### ISSUE THREAD

**Issue by lyz810** [Tencent/vConsole#398]
vConsole Version: 3.5.1
目前清除了下面几种cookie
```
document.cookie = "".concat(o, "=;expires=Thu, 01 Jan 1970 00:00:00 GMT"),
document.cookie = "".concat(o, "=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/"),
document.cookie = "".concat(o, "=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain=.").concat(e.split(".").slice(-2).join("."))
```

待清除的cookie:
httpOnly: false
domain: .a.b.com
path: /
页面：a.b.com/123
清除结果：失败
根据如上代码，可以清除domain为`.b.com`、`a.b.com`的cookie但不能清除domain设置为`.a.b.com`的cookie
可以多兼容下

**Comment by Maizify** [comment]
谢谢反馈，这个现象确实存在，当时对域名考虑欠妥了。将在下一个版本修复。
