### ISSUE TITLE
Android5.1 兼容问题

### ISSUE THREAD

**Issue by hec9527** [Tencent/vConsole#404]
环境信息：
| env | version|
| ---| ---|
|vConsole Version|3.6.0|
| phone brand| vivo X7|
|android version|  5.1|
|chrome version| 39.0.0.0|

Bug截图：
![截屏_20210524_173033](https://user-images.githubusercontent.com/28671232/119329488-dc89fd80-bcb7-11eb-8572-41d2503a804c.jpg)
![S10524-17292396](https://user-images.githubusercontent.com/28671232/119329598-f9263580-bcb7-11eb-820e-de501d1596c8.png)

问题背景：
     1. 如果采用npm安装，webpack打包的方式在项目中引用vconsole，在以上环境中无法打开页面，直接白屏
     2. 如果通过引入 vconsole.min.js，页面可以打开，但是只能加载默认插件(log)，并且颜色无法显示

问题复现：
     1. 如果需要复现上面的问题，使用`vivo X7`设备（自带浏览器替换了高版本内核，可以安装via浏览器使用自带内核）
     2. 或者通过镜像站下载 `chrome 39`，在高于39版本可以复现  [Chrome Apk Download(all version)](https://www.apkmirror.com/uploads/?q=chrome)  或者    [click to download Chrome 39](https://www.apkmirror.com/wp-content/uploads/2014/12/547f8b23930f3/com.android.chrome-39.0.2171.93-2171093-minAPI14.apk?verify=1621848096-n9WqDPr69mb6ETIVa--h33_D4m9dI7-qjjkeemHQRoo)

**Comment by Maizify** [comment]
先问下，3.6.0以前的版本，会这样吗？

**Comment by hec9527** [comment]
我刚刚试了一下3.5.2版本，直接报错了

![image](https://user-images.githubusercontent.com/28671232/119343713-6a221900-bcc9-11eb-9238-4ae4a1424dea.png)

**Comment by Maizify** [comment]
你的测试机系统和chrome版本太低了，有些比较新的JS语法没支持到……

**Comment by amazingdudu** [comment]
> 你的测试机系统和chrome版本太低了，有些比较新的JS语法没支持到……

4.4-5.1的安卓机型还是有一定占有率，新语法完全可以通过babel解决。初步判断，应该为使用for of循环以及entries等api造成的。

![image](https://user-images.githubusercontent.com/30384547/119452370-de5fc980-bd68-11eb-9992-75aa859f46d4.png)

**Comment by amazingdudu** [comment]
> > 你的测试机系统和chrome版本太低了，有些比较新的JS语法没支持到……
> 
> 4.4-5.1的安卓机型还是有一定占有率，新语法完全可以通过babel解决。初步判断，应该为使用for of循环以及entries等api造成的。
> 
> ![image](https://user-images.githubusercontent.com/30384547/119452370-de5fc980-bd68-11eb-9992-75aa859f46d4.png)

![image](https://user-images.githubusercontent.com/30384547/119452465-fb949800-bd68-11eb-852f-bc076e48c465.png)
![image](https://user-images.githubusercontent.com/30384547/119452491-04856980-bd69-11eb-9d8a-b31d4a0cbb89.png)
![image](https://user-images.githubusercontent.com/30384547/119452533-0ea76800-bd69-11eb-8568-b19eea8da8d6.png)

**Comment by Maizify** [comment]
![image](https://user-images.githubusercontent.com/215664/119456290-1ff27380-bd6d-11eb-8de9-3b93c4c0ce26.png)

实际上编译出来已经没有 `for...of` 这种语法了，如上图。
反倒是你最后截图的`.entries()`可能有问题，我改了一下写法，你可以试下dev分支里的`dist/vconsole.min.js`。

**Comment by hec9527** [comment]
在最新的版本3.7中， 依然存在兼容问题

**Comment by FoooooooF** [comment]
![image](https://user-images.githubusercontent.com/27750722/120603920-15c42980-c47f-11eb-8f40-af2303128ece.png)
这个箭头函数没有编译,在低版本浏览器上应该也有问题

**Comment by Maizify** [comment]
> 在最新的版本3.7中， 依然存在兼容问题

有具体的报错信息吗？

**Comment by hec9527** [comment]
> > 在最新的版本3.7中， 依然存在兼容问题
> 
> 有具体的报错信息吗？


![image](https://user-images.githubusercontent.com/28671232/123028640-41995600-d412-11eb-8dcb-40a82ca7a520.png)

应该是箭头函数的问题， 把编译目标设置为ES5应该就可以了

**Comment by Maizify** [comment]
试下v3.8.0。

**Comment by hec9527** [comment]
![image](https://user-images.githubusercontent.com/28671232/123195683-2c3c2e80-d4db-11eb-96eb-86a7a1769db0.png)

包含ES6的解构和默认值的语法

**Comment by billwing** [comment]
> ![image](https://user-images.githubusercontent.com/28671232/123195683-2c3c2e80-d4db-11eb-96eb-86a7a1769db0.png)
> 
> 包含ES6的解构和默认值的语法 @Maizify

3.8.0 遇到同样问题（Chrome 49）

**Comment by Maizify** [comment]
> 包含ES6的解构和默认值的语法 @Maizify

原因是构建时排除了node_modules，导致外部文件没被转换。下一个版本改进。
