### ISSUE TITLE
vconsole 抓取 options 403 请求的时候，响应的状态码有误，返回是 0 

### ISSUE THREAD

**Issue by SensitiveMix** [Tencent/vConsole#405]

**Comment by SensitiveMix** [comment]
![image](https://user-images.githubusercontent.com/16094680/119609764-b2a51800-be2a-11eb-8e5c-a9e8b34616cf.png)

**Comment by SensitiveMix** [comment]
复杂请求的时候，首先会发送 Options 请求来探测资源，抓包发现是 Options 请求 403 了，但是 Vconsole 这边显示的有些问题，请求方法还是 POST，并且 Response Code 是 0

**Comment by SensitiveMix** [comment]
@fireyy @akai @Maizify @zswang

**Comment by Maizify** [comment]
![image](https://user-images.githubusercontent.com/215664/119789175-6aa6f380-bf05-11eb-988e-3783833276e3.png)

你用的是哪个版本？我在最新版本中测试，没问题。

**Comment by SensitiveMix** [comment]
用的是 3.6.1，status 返回的是 0，用的 axios 发送的请求，你这个正常的也是用的这个库么 @Maizify

**Comment by Maizify** [comment]
vConsole里没有修改request请求的METHODS（若获取不到则默认为 GET）。所以如果发送时是 OPTIONS 请求，那么会原封不动显示出来。看看是否 Axios 使用了 POST 来发送请求？

**Comment by SensitiveMix** [comment]
这个目前定位到了，是出现跨域请求到时候，Response Code 返回是 0

**Comment by Maizify** [comment]
> 这个目前定位到了，是出现跨域请求到时候，Response Code 返回是 0

跨域是浏览器级别的拦截，JS貌似没有办法识别到这个错误，所以这里的状态被迫停留在初始值0了。
