### ISSUE TITLE
为什么不打包成es5的版本？

### ISSUE THREAD

**Issue by HakunaMatata052** [Tencent/vConsole#407]
vConsole Version:
为什么不打包成es5的版本？低版本游览器无法兼容es6

**Comment by Maizify** [comment]
vConsole版本号、具体报错是？目前有用到一些polyfill，不知是否没覆盖你遇到的情况。

**Comment by Maizify** [comment]
调整了下webpack配置，现在3.8.0打包到ES5了，可以试下。
