### ISSUE TITLE
是否可以提供 复制CURL的功能？

### ISSUE THREAD

**Issue by Mark24Code** [Tencent/vConsole#410]
vConsole Version:

**Comment by Maizify** [comment]
可以有，不过可能会以其他结构化形式复制出来。

**Comment by JslinSir** [comment]
> 可以有，不过可能会以其他结构化形式复制出来。
怎么复制呢？

**Comment by ManiaciaChao** [comment]
对于 fetch，有个现成的解析器 [leoek/fetch-to-curl](https://github.com/leoek/fetch-to-curl)
xhr 应该也有类似的

**Comment by Maizify** [comment]
可以尝试下v3.10.0版本，现在支持复制各个属性。

**Comment by lishichao1002** [comment]
复制各个属性还是不方便给到后端使用，能在工具顶层提供curl的能力吗？ @Maizify

**Comment by webstager** [comment]
> 可以尝试下v3.10.0版本，现在支持复制各个属性。

你好，具体如何配置可以复制curl？能提供一个配置demo吗？
