### ISSUE TITLE
控制台输出的对象的折叠/展开操作区域（三角形）能不能扩大，手指粗的人经常点半天点不开

### ISSUE THREAD

**Issue by tcatche** [Tencent/vConsole#415]
rt

**Comment by tcatche** [comment]
![image](https://user-images.githubusercontent.com/7147399/123207235-a70f4480-d4ef-11eb-95fa-cab89021a621.png)

**Comment by Maizify** [comment]
三角后面的一整行文本都是可点击区，不用非得去点这个三角形的。

**Comment by tcatche** [comment]
> 三角后面的一整行文本都是可点击区，不用非得去点这个三角形的。

之前在一款内部的app的webview打开的网页点击的时候文本点击都是展不开的，我还还以为热点只有这么大=_=!
