### ISSUE TITLE
编译报错You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by frankyeyq** [Tencent/vConsole#416]
vConsole Version:
3.8.0
编译报错
ERROR in ./node_modules/_vconsole@3.8.0@vconsole/dist/vconsole.min.js
Module parse failed: Unexpected token (10:1153)
You may need an appropriate loader to handle this file type.
|  * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
|  */

**Comment by Maizify** [comment]
感谢反馈，原因出在vConsole构建时未对第三方库做转换，导致一个新语法 `catch {}` 报错。将在下一个小版本里修复。
