### ISSUE TITLE
不带域名的 URL 如果参数当中有 http，会报错。

### ISSUE THREAD

**Issue by git-patrickliu** [Tencent/vConsole#420]
vConsole Version: 3.8.1

Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at o.a.getURL (vconsole.min.js:10)
    at window.fetch (vconsole.min.js:10)
    at HTMLScriptElement.script.onload (<anonymous>:5:3)

复现路径

`const script = document.createElement('script');
script.src = 'https://unpkg.com/vconsole@3.8.1/dist/vconsole.min.js';
script.onload = function () {
  var vConsole = new window.VConsole();
  fetch('/?t=http');
}
document.querySelector('body').appendChild(script);`

**Comment by Maizify** [comment]
已在v3.9.0修复，请尝试一下。
