### ISSUE TITLE
如何关闭pc端下的[system]打印

### ISSUE THREAD

**Issue by linlwss** [Tencent/vConsole#422]
在pc端下，VConsole 会打印一些[system]，如何关闭？
![669](https://user-images.githubusercontent.com/47050388/124558293-057fdf80-de6d-11eb-8e57-d276fc62eeea.png)

**Comment by Maizify** [comment]
初始化的时候，自定义`defaultPlugins`，不传入`'system'`就好。参考文档： https://github.com/Tencent/vConsole/blob/master/doc/public_properties_methods_CN.md
