### ISSUE TITLE
接口信息显示建议

### ISSUE THREAD

**Issue by chenxinan** [Tencent/vConsole#425]
vConsole Version: 3.8.1
![image](https://user-images.githubusercontent.com/26038906/125044485-96a1c100-e0ce-11eb-895f-2770a16d2980.png)
值太长能不能换行显示 不然要滚动才能看的全

![image](https://user-images.githubusercontent.com/26038906/125044624-b76a1680-e0ce-11eb-8ddd-3bcedff7e592.png)
request payload能恢复到以前一样吗，上图是新版本的，下图是旧版本的
![image](https://user-images.githubusercontent.com/26038906/125044789-e4b6c480-e0ce-11eb-9dfe-bf9bffd47421.png)

**Comment by Maizify** [comment]
![image](https://user-images.githubusercontent.com/215664/125758611-8193730d-17f9-4dc6-be24-97dc148640ec.png)
正常来说是这样的，会以key-value形式展示。
你POST的数据是不是一个字符串形式的JSON？

**Comment by Maizify** [comment]
看来确实是POST一个JSON字符串的时候会出现这个问题。下一个版本会修正，先尝试解析成JSON。
