### ISSUE TITLE
Cannot set property fetch of #<Window> which has only a getter

### ISSUE THREAD

**Issue by qianlongo** [Tencent/vConsole#427]
vConsole Version: 3.8.1
![image](https://user-images.githubusercontent.com/13052156/125428782-53979b15-db63-4b1b-bccc-1ddf85ed199f.png)
问题如图

**Comment by Maizify** [comment]
请问是否有引入其他第三方库？

**Comment by jayzAlex** [comment]
https://github.com/Tencent/vConsole/issues/662 issues close too quick
