### ISSUE TITLE
【3.9.0】TypeError: Cannot read property 'view' of undefined @ o.r.onChildAdd

### ISSUE THREAD

**Issue by nebulium** [Tencent/vConsole#436]
安卓手机webview中打开页面报如标题错误，变现为页面操作卡顿，将vconsole销毁后就无问题，具体版本信息如下，某些内部信息做了脱敏处理，麻烦帮忙看下：

- vConsole Version: 3.9.0
- UserAgent：Mozilla/5.0 (Linux; Android 10; ***) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.186 Mobile Safari/537.36

**Comment by ManiaciaChao** [comment]
看起来是 Element 面板的问题。我这边还没复现，你这样试下：
```
const vConsole = new VConsole({ defaultPlugins: ['element'] }); // 只开 Element 面板
```
然后看看报错是什么。

**Comment by Maizify** [comment]
重构了一版，可以尝试下v3.10.0版本。有问题再开issue吧。
