### ISSUE TITLE
3.9.0版本在部分手机上不显示Storage

### ISSUE THREAD

**Issue by Yolanda624** [Tencent/vConsole#439]
vConsole Version: 3.9.0

**Comment by Yolanda624** [comment]
最新版3.9.0 手机上调试时没有Storage项，只有前四项。并且会报script error的错误。如果用pc的移动模式查看就有storage，不报错。

出错的两部手机是andriod10，一个vivoS5，一个红米K30

**Comment by Maizify** [comment]
感谢反馈，可以试下v3.9.1。

**Comment by id77** [comment]
我测试3.9.1在 IOS Alook 软件下，进入m.jd.com也不行。没有Storage项。

3.8.1却可以。
![image](https://user-images.githubusercontent.com/9592236/127154860-f97efb8d-2585-4af0-864b-187f17543ea8.png)

**Comment by Maizify** [comment]
> 我测试3.9.1在 IOS Alook 软件下，进入m.jd.com也不行。没有Storage项。
> 
> 3.8.1却可以。
收到，我们再看看。
