### ISSUE TITLE
react ssr framework next.js 引入报错

### ISSUE THREAD

**Issue by victorykong** [Tencent/vConsole#441]
vConsole Version: lastest

`
useEffect(() => {
    if (process.browser) {
      new VConsole();
    }
  }, []);
`

![image](https://user-images.githubusercontent.com/50655436/127121284-edc3bab6-0c2f-4148-b705-a2b58cd31325.png)

**Comment by sfsoul** [comment]
same error

**Comment by sfsoul** [comment]
> vConsole Version: lastest
> 
> `useEffect(() => { if (process.browser) { new VConsole(); } }, []);`
> 
> ![image](https://user-images.githubusercontent.com/50655436/127121284-edc3bab6-0c2f-4148-b705-a2b58cd31325.png)

![image](https://user-images.githubusercontent.com/18617129/132469535-0ac64bd4-ff7f-411d-a31d-fee07a925630.png)
用这种方式可以解决

**Comment by Maizify** [comment]
因为目前vConsole仍是面向浏览器端，所以如果在node环境import vConsole，就会有报错。
接下来我们目标是做到如果不new vConsole，node环境就不会报错。但是由于一些第三方库没有做好兼容，所以这里还需要时间去做改造。
