### ISSUE TITLE
globalThis is not defined，v3.9.1在企业微信里还是不行哦

### ISSUE THREAD

**Issue by c-sopoo** [Tencent/vConsole#443]
感谢反馈，可以试下v3.9.1。

_Originally posted by @Maizify in https://github.com/Tencent/vConsole/issues/438#issuecomment-887318208_

**Comment by Maizify** [comment]
get 我们再看看。

**Comment by c-sopoo** [comment]
在企业微信内就报错 `globalThis is not defined`，


![image](https://user-images.githubusercontent.com/54697751/127301783-59e4cefe-2549-46f9-b833-2cca8335958e.png)
![image](https://user-images.githubusercontent.com/54697751/127299938-eee7bb03-d01b-46bd-9023-2a8e28f033ab.png)

然后找了一个低版本的58的浏览器，也报错，可能是兼容问题
![image](https://user-images.githubusercontent.com/54697751/127301376-ce65af86-b2e3-49d0-9f68-fc6c62edb345.png)

**Comment by umarufans** [comment]
同，3.9.1 在 Android UC 里也报了相同的错，iOS 是 OK 的

**Comment by wz57c** [comment]
这边也遇到了同样的问题，低版本的android webview里

**Comment by syf-123** [comment]
遇到同样的问题，将vConsole版本降为3.8.1，正常运行，找了我好几天，这个3.9.1版本太捞了

**Comment by leviweili** [comment]
IOS 11.0.1系统的WKWebview上也会报错 vConsole是3.9.1
ReferenceError: Can't find variable: globalThis undefined

**Comment by Maizify** [comment]
可以尝试下v3.10.0版本。

**Comment by zcrkey** [comment]
vConsole v3.11.0

![image](https://user-images.githubusercontent.com/39945923/148181321-a4df8804-42f6-41c0-bd59-cbe06b20f874.png)
