### ISSUE TITLE
Error类型在vconsole中显示空Error对象，没有详细信息

### ISSUE THREAD

**Issue by liangxuev** [Tencent/vConsole#448]
![image](https://user-images.githubusercontent.com/23612740/128134773-9482aaff-a76d-4594-9f22-a05f3f66b8af.png)
![image](https://user-images.githubusercontent.com/23612740/128134862-2606cc77-3fa0-4767-8afc-a3d653be2b30.png)

经排查是由于vconsole中JSON.stringify() console参数导致的

![image](https://user-images.githubusercontent.com/23612740/128135316-09842287-7aed-4747-b2ab-3dcca8b05b2d.png)

这个问题可以处理吗？

**Comment by Maizify** [comment]
收到，我们处理下。

**Comment by toyobayashi** [comment]
3.9.5 版本依然存在

暂时的解决方案可以在 vconsole 加载后 monkeypatch 掉 console 输出

```js
const logMethods = ['log', 'info', 'warn', 'error']
const transformError = function (item) {
  if (item instanceof Error) {
    const err = {
      message: item.message,
      stack: item.stack
    }
    Object.defineProperty(err, 'name', { value: item.name })
    if (typeof Symbol === 'function') {
      Object.defineProperty(err, Symbol.toStringTag, { value: item.name })
    }
    Object.setPrototypeOf(err, item.constructor.prototype)
    return err
  }
  return item
}
logMethods.forEach(method => {
  const oldMethod = console[method]
  console[method] = function () {
    oldMethod.apply(console, Array.prototype.map.call(arguments, transformError))
  }
})
```

**Comment by liangxuev** [comment]
好的，感谢您的回复！我们目前已经rewrite了console方法，根据类型处理后，再输出到vconsole。也还是希望vconsole框架早日有方案可以进行优化此功能相关模块。后续有时间我也会跟进调研此问题，有合适的方案在github上再和您这边反馈沟通。



---- 回复的原邮件 ----
| 发件人 | Fenglin ***@***.***> |
| 日期 | 2021年11月25日 16:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Tencent/vConsole] Error类型在vconsole中显示空Error对象，没有详细信息 (#448) |

3.9.5 版本依然存在

暂时的解决方案可以在 vconsole 加载后 monkeypatch 掉 console 输出

constlogMethods=['log','info','warn','error']consttransformError=function(item){if(iteminstanceofError){consterr={message: item.message,stack: item.stack}Object.defineProperty(err,'name',{value: item.name})if(typeofSymbol==='function'){Object.defineProperty(err,Symbol.toStringTag,{value: item.name})}Object.setPrototypeOf(err,item.constructor.prototype)returnerr}returnitem}logMethods.forEach(method=>{constoldMethod=console[method]console[method]=function(){oldMethod.apply(console,Array.prototype.map.call(arguments,transformError))}})

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Maizify** [comment]
感谢PR，由于最近在重构代码，所以才留意到这个PR。
经过测试，重构后的vconsole已经可以正常显示楼顶所示的Error message了。
这个版本是v3.10.0，预计将于近期发布。

![image](https://user-images.githubusercontent.com/215664/145219855-e3eb897a-765d-474c-b709-6e6c2bf41a4c.png)
![image](https://user-images.githubusercontent.com/215664/145219902-54f181bb-10f2-437b-9a68-e56dd6157bf9.png)

**Comment by liangxuev** [comment]
好的，那我最近关注一下更新，试用后也考虑在我们目前的框架中更新vconsole的版本。👍



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月08日 21:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Tencent/vConsole] Error类型在vconsole中显示空Error对象，没有详细信息 (#448) |

感谢PR，由于最近在重构代码，所以才留意到这个PR。
经过测试，重构后的vconsole已经可以正常显示楼顶所示的Error message了。
这个版本是v3.10.0，预计将于近期发布。




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Maizify** [comment]
可以尝试下v3.10.0版本。
