### ISSUE TITLE
怎么在小程序调试面板复制日志信息

### ISSUE THREAD

**Issue by RolkerMan** [Tencent/vConsole#449]
vConsole Version:
网页版可以复制，小程序里不可复制

**Comment by Lyfei** [comment]
同问，哥们找到方法时不妨分享一下

**Comment by TuKun33** [comment]
同问，网页版也不能复制 微信和企业内置浏览器打开都不能复制

**Comment by Maizify** [comment]
目前小程序的版本还未更新到最新版，所以还不能复制。等待官方更新即可。

**Comment by Maizify** [comment]
> 同问，网页版也不能复制 微信和企业内置浏览器打开都不能复制

@TuKun33 网页里的vConsole是你自己引入的，更新到最新版就可以了。
