### ISSUE TITLE
[Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. 

### ISSUE THREAD

**Issue by YG-07** [Tencent/vConsole#452]
vConsole Version:
3.9.1

**Comment by YG-07** [comment]
I found the problem is: this.$route is output in the created function of the component. Just delete the line of code.
created() {
   console.log(this.$route);
}

**Comment by YG-07** [comment]
I found the problem is: this.$route is output in the created function of the component. Just delete the line of code.
created() {
   console.log(this.$route);
}

**Comment by yanghuanrong** [comment]
I had the same problem

**Comment by Maizify** [comment]
It seems to be caused by your own code? If you delete vConsole but keep console.log(), will the application still report this error?

**Comment by moketao** [comment]
![image](https://user-images.githubusercontent.com/3243514/140498172-b51eb819-42de-46db-a0e6-1ecffadc29c3.png)

**Comment by moketao** [comment]
![image](https://user-images.githubusercontent.com/3243514/140498273-80dc5646-981b-4ded-8f8e-7efa52fadf34.png)

**Comment by moketao** [comment]
"function" == typeof this.console[e.logType] && this.console[e.logType].apply(window.console, e.logs)

**Comment by moketao** [comment]
版本是 v3.9.4， 不太看得懂为什么会报错，可能跟 vue 有关

**Comment by yanghuanrong** [comment]
> 版本是 v3.9.4， 不太看得懂为什么会报错，可能跟 vue 有关

你可以尝试使用3.7的版本。我用3.7的版本不会出现这个问题

**Comment by moketao** [comment]
试了一下，3.7 我这边也还是会报错，"vconsole": "^3.7.0"

**Comment by Maizify** [comment]
@moketao @yanghuanrong 请问你们是打印了什么对象？

**Comment by Maizify** [comment]
vConsole 3.10.0里重写了内部逻辑，没有再调用 toJSON 等相关操作，应该不会出现这个报错了。
