### ISSUE TITLE
坑货

### ISSUE THREAD

**Issue by zhuzi0125** [Tencent/vConsole#458]
使用了vsconsole  json.stringfiy 就报错 太坑了

**Comment by zhuzi0125** [comment]
使用了vsconsole json.stringfiy 转化就不标准了

**Comment by Maizify** [comment]
请问是否使用了低版本的vConsole？最新的版本里应该没有这个问题了。

**Comment by lovetingyuan** [comment]
fetch也有问题。。。重写也不遵循标准

**Comment by Maizify** [comment]
> fetch也有问题。。。重写也不遵循标准

请问是哪里有问题？

**Comment by lovetingyuan** [comment]
fetch 一个失败的网络请求，正常应该直接调用catch，但是添加了vconsole之后，却调用了then，调用了then也应该返回Response吧，但是then的参数却是undefined

**Comment by Maizify** [comment]
> fetch 一个失败的网络请求，正常应该直接调用catch，但是添加了vconsole之后，却调用了then，调用了then也应该返回Response吧，但是then的参数却是undefined

收到。vConsole内部catch住了error，导致外部catch不到，后续会修复下，throw出来。
