### ISSUE TITLE
在OPPO、vivo小游戏打印输出不到系统面板

### ISSUE THREAD

**Issue by zyqq** [Tencent/vConsole#461]
vConsole Version:最新
![211633694749_ pic_hd](https://user-images.githubusercontent.com/15664576/136553887-461dae0a-3424-4b97-a1d1-c71ed46f4dee.jpg)
console.unit('[system]',1) 只能输出到log面板，在system面板看不到
![221633694751_ pic_hd](https://user-images.githubusercontent.com/15664576/136553919-ed3f2676-a9b4-42e9-b19c-e6f91a806bd3.jpg)
但是console.log('[system]')可以输出到system面板
怀疑是自动把两个参数合并成一个参数了，试着传了数组还是不行
![image](https://user-images.githubusercontent.com/15664576/136554449-3131f615-3e07-44d9-901c-1dd685d00195.png)

**Comment by Maizify** [comment]
抱歉看迷糊了。
目前所有版本都不支持 console.unit，这似乎并不是一个标准的 `console` 方法。
我这里使用 3.9.1 版本无法复现你说的情况，有无可能是其他库（比如游戏框架）再次勾住了 console.log 方法，从而覆盖了 vConsole 的逻辑？

**Comment by Maizify** [comment]
估计楼主这里的console.log不是原生的方法，可能是覆盖了原生逻辑，会将参数合并成一个。
目前vConsole规则是需要全匹配第一个参数，如果放宽限制，可能会带来潜在的正则匹配效率问题，所以暂时没有修改的打算。
