### ISSUE TITLE
uglifyjs-webpack-plugin 压缩文件报错

### ISSUE THREAD

**Issue by licongwell** [Tencent/vConsole#468]
vConsole Version: 3.9.4

vconsole.min.js 里面有es6语法，使用uglifyjs-webpack-plugin 压缩报错。

之前 3.2.0版本没有这个情况

![30A872B54E55EB7BF4FAE23F70F62C3C](https://user-images.githubusercontent.com/20041165/139664410-eec28d0a-adc0-4e74-a060-13afb0a9dc00.jpg)

**Comment by Maizify** [comment]
从3.9.0开始vConsole里用了svelte，它目前最低只支持到ES6，这个限定比较难突破。
你可以尝试配置一下webpack以兼容vConsole ES6的情况。

**Comment by Maizify** [comment]
感谢反馈，这是由3.9.0引入的Svelte造成的。现在会对Svelte产生的代码再做一次babel转换，应该不会再带ES6语法了。
