### ISSUE TITLE
[bug]<v3.9.2>URIError 报错

### ISSUE THREAD

**Issue by iHaroro** [Tencent/vConsole#470]
项目使用vconsole@3.9.2时报错，相关环境：
React: 17.0.1
Google Chrome：94.0.4606.81（正式版本） (x86_64)
![image](https://user-images.githubusercontent.com/22785090/140025803-d9d5f8ee-1c21-4812-8fc6-5219198ce98e.png)

相关demo仓库：https://github.com/iHaroro/react-entry-template
分支 master 回退版本3.8.2，正常使用
分支 hotfix-vconsole-3.9.4 使用3.9.2及以上版本，异常报错

**Comment by Maizify** [comment]
感谢反馈。应该是 decode 网址里的 query 参数的时候出错了，现已加入 try catch 保护。预计会在 3.9.5 里修复。
