### ISSUE TITLE
cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by zhixiangw** [Tencent/vConsole#471]
vConsole Version: 3.9.4'
报错导致项目fetch失败。去掉vconsole后，页面恢复正常。详情如下：
![WechatIMG51](https://user-images.githubusercontent.com/18670896/140717945-88114c91-56d1-47d9-a3d1-f9d841853472.jpeg)
![WechatIMG53](https://user-images.githubusercontent.com/18670896/140717963-29e33c74-f071-4657-83de-2d45b1795ab3.jpeg)
![WechatIMG52](https://user-images.githubusercontent.com/18670896/140717977-f1a57eb0-4cd9-4b1c-bb7d-3aefed7991b3.jpeg)

**Comment by Maizify** [comment]
谢谢反馈。
可否贴下完整的Error信息？屏蔽掉敏感网址就行。

**Comment by Maizify** [comment]
请尝试下3.9.5版本。
