### ISSUE TITLE
tab点击切换无效问题

### ISSUE THREAD

**Issue by xiaoyindong** [Tencent/vConsole#477]
vConsole Version:  3.5.1+

logs中下面代码会导致个别手机click事件失效，无法切换plugin tab，仅限logs插件。修改core.svelte中的click事件为touchend可解决。

```js
$.one('.vc-log', this.$tabbox).insertAdjacentElement('beforeend', $line);
```

![image](https://user-images.githubusercontent.com/27474244/142601813-15bd3512-5026-4eb5-a92e-faefe6a81d64.png)

**Comment by Maizify** [comment]
这里的原因是……？

**Comment by xiaoyindong** [comment]
实话实说，我也没找到原因，只是注释了这段代码就可以切换至network等tab了，不然就会一直卡在log tab，点击的时候会打印一条截图的log。当然把click事件修改为touchend也可以正常切换。正常切换是不会打印图片中的log的。
我这边只有一台测试机会这样，其它手机基本都是正常的。3.5.1之前的版本正常。从3.5.2开始有这个问题。

**Comment by xiaoyindong** [comment]
实话实说，我也没找到原因，只是注释了这段代码就可以切换至network等tab了，不然就会一直卡在log tab，点击的时候会打印一条截图的log。当然把click事件修改为touchend也可以正常切换。正常切换是不会打印图片中的log的。
我这边只有一台测试机会这样，其它手机基本都是正常的。3.5.1之前的版本正常。从3.5.2开始有这个问题。

**Comment by xiaoyindong** [comment]
> 实话实说，我也没找到原因，只是注释了这段代码就可以切换至network等tab了，不然就会一直卡在log tab，点击的时候会打印一条截图的log。当然把click事件修改为touchend也可以正常切换。正常切换是不会打印图片中的log的。
> 我这边只有一台测试机会这样，其它手机基本都是正常的。3.5.1之前的版本正常。从3.5.2开始有这个问题。

**Comment by xiaoyindong** [comment]
> 实话实说，我也没找到原因，只是注释了这段代码就可以切换至network等tab了，不然就会一直卡在log tab，点击的时候会打印一条截图的log。当然把click事件修改为touchend也可以正常切换。正常切换是不会打印图片中的log的。
> 我这边只有一台测试机会这样，其它手机基本都是正常的。3.5.1之前的版本正常。从3.5.2开始有这个问题。

**Comment by xiaoyindong** [comment]
> 这里的原因是……？

我也没找到原因，只是注释了这段代码就可以切换至network等tab了，不然就会一直卡在log tab，点击的时候会打印一条截图的log。当然把click事件修改为touchend也可以正常切换。正常切换是不会打印图片中的log的。
我这边只有一台测试机会这样，其它手机基本都是正常的。3.5.1之前的版本正常。从3.5.2开始有这个问题。

**Comment by Maizify** [comment]
3.7.0才引入的svelte，而3.10.0-rc（正在开发中）才有core.svelte文件。你是从3.5.2一路试到最新版本都会这样？

**Comment by xiaoyindong** [comment]
> 3.7.0才引入的svelte，而3.10.0-rc（正在开发中）才有core.svelte文件。你是从3.5.2一路试到最新版本都会这样？

是的，也可以说我是从1.0一直试到了3.9.x，只因为我想用可以使用的最新版本....

然后我fork了最新版本代码，发现了修改core.svelte和事件名称可以正常使用，其他版本并没有试验。(我猜测可能是初始化追加logs的时候，是不是阻塞了click事件)

**Comment by Maizify** [comment]
辛苦了，有耐心。
这个表现确实比较奇怪，接下来我尝试下，如果不行就再尝试touchend的方案。
