### ISSUE TITLE
Network JSON 响应没格式化

### ISSUE THREAD

**Issue by toyobayashi** [Tencent/vConsole#486]
vConsole Version: 3.10.0

没换行，有很长的横向滚动条，不方便查看响应数据，3.9.5 不会这样

![image](https://user-images.githubusercontent.com/23353576/146703527-ffaf51c2-2f24-4263-a4a1-19e6b0dcd65b.png)

**Comment by Maizify** [comment]
谢谢反馈。3.10.0重构了JSON逻辑，导致丢失了格式化逻辑。下一版补上。
