### ISSUE TITLE
官方提供的 Demo 面板的 Tab 按钮点击没反应

### ISSUE THREAD

**Issue by avwo** [Tencent/vConsole#487]
vConsole Version: 3.10.0

http://wechatfe.github.io/vconsole/demo.html

![image](https://user-images.githubusercontent.com/11450939/146925520-6f7e41ff-cf24-4440-98d4-8937f158a9ab.png)

**Comment by Maizify** [comment]
这里用了touch而非click事件进行触发，所以PC模式下会不生效。接下来的版本会处理一下这个情况。
