### ISSUE TITLE
切换到Element面板再隐藏vconsole导致死循环

### ISSUE THREAD

**Issue by toyobayashi** [Tencent/vConsole#491]
vConsole Version: 3.10.1

页面用了 Swiper 3。

![image](https://user-images.githubusercontent.com/23353576/147435033-817f23da-1898-4d37-bcc9-1b4d9c214c81.png)

死循环位置可能不是截图这里，但是确实隐藏之后页面就卡死了，切换其他tab再隐藏就无法重现此问题。

**Comment by Maizify** [comment]
感谢反馈。有无可复现的页面？

**Comment by toyobayashi** [comment]
@Maizify 是否可以留个微信或者邮箱什么的，因为是公司的项目里遇到的，不方便发出来

**Comment by Maizify** [comment]
微信群还没建，可以在QQ群找我，邮箱：`emhpa2FpbWFpQHRlbmNlbnQuY29t`
![](https://github.com/Tencent/vConsole/blob/dev/doc/screenshot/qq_group.png)

**Comment by Maizify** [comment]
找到原因了。是因为未妥善处理 Comment 类型的 Node 节点导致的死循环。会在下一个版本中修复。

**Comment by Maizify** [comment]
已在v3.11.0中支持。
