### ISSUE TITLE
put 请求缺少请求参数（Request Paylod）项 

### ISSUE THREAD

**Issue by TTcom** [Tencent/vConsole#493]
vConsole Version: 3.10.1

http请求为put请求并且包含请求参数时在vconsole中缺失Request Paylod项，无法查看请求参
![bug](https://user-images.githubusercontent.com/29853303/147625316-0a9a8bd7-633d-4573-9e47-8e993d9f482a.png)
数

**Comment by Maizify** [comment]
谢谢反馈。粗看了下代码实现，目前是 POST 的时候才会取payload。一会我复现下。

**Comment by Maizify** [comment]
已在v3.11.0中支持。
