### ISSUE TITLE
vConsole 导致 react 的热更新失败

### ISSUE THREAD

**Issue by ywwhack** [Tencent/vConsole#496]
vConsole Version: 3.11.0 

## 报错信息如下：
![image](https://user-images.githubusercontent.com/8746197/147742799-625d913a-7193-4220-be6d-8b3ce4b2943d.png)

## 在报错的地方，打个断点，捕获到的信息如下：
![image](https://user-images.githubusercontent.com/8746197/147741652-3fed6373-5ec1-487d-b718-846d1cd9a237.png)

**Comment by ywwhack** [comment]
看了下源码，应该是 https://github.com/Tencent/vConsole/commit/dbd7765ebf80b273359cf5186e8b6b5871c2ff0a#diff-a0e64af60dc13dd969ec645277aa2b6b6b9dfc47a9ebe7ef6b240b73daa51605R308 这行代码导致的报错

**Comment by ike666666** [comment]
https://github.com/Tencent/vConsole/blob/3165e627af43c24d8670527f1d7943a57ebf0e2a/src/network/network.model.ts#L309
是这一行导致的，第二个参数是非必要的，但是代码不严谨没做判断，正常ts会检测出来的。 让作者加个？号就可以了，init?.body

**Comment by Maizify** [comment]
感谢反馈，已在 #500 中修复，预计在3.11.1中发布。
