### ISSUE TITLE
bug: v3.10.1上cookie的删除按钮无效

### ISSUE THREAD

**Issue by ChloeFancy** [Tencent/vConsole#499]
vConsole Version:
3.10.1

feature: 希望支持一键清除localStorage/cookie/sessionStorage

**Comment by Maizify** [comment]
你的cookie domain是不是不在当前域名下？比如在上级的域中。

**Comment by neohan666** [comment]
> 你的cookie domain是不是不在当前域名下？比如在上级的域中。

我的也删不了，是在上级域名中。

**Comment by Maizify** [comment]
本地复现了下，也许是 `cookie-storage` 的问题，接下来我再进一步定位看看。

**Comment by Maizify** [comment]
已在v3.11.2中发布。
