### ISSUE TITLE
init.body 能否修改下 改成init?.body,因为你们的第二个参数不是必须的。

### ISSUE THREAD

**Issue by ike666666** [Tencent/vConsole#500]
https://github.com/Tencent/vConsole/blob/3165e627af43c24d8670527f1d7943a57ebf0e2a/src/network/network.model.ts#L309

**Comment by ike666666** [comment]
因为代码写的是window.fetch 全局覆盖了fetch，如果不修改会造成业务代码中的fetch 用到这个fetch还必须传第二个参数。

**Comment by Maizify** [comment]
已在3.11.1中发布。
