### ISSUE TITLE
Support for NextJS

### ISSUE THREAD

**Issue by skydive-missile** [Tencent/vConsole#503]
vConsole Version: Latest

Is anyone have been done using with NextJS

**Comment by Maizify** [comment]
You can import vConsole on the browser side (like Vue or React), but don't import it on the nodejs side. 
vConsole does not yet support SSR as it currently relies on many browser environments.

**Comment by WangCao** [comment]
build a vconsole component
`
const VConsole = () => {
	useEffect(() => {
		ISDEV && new vconsole();
	}, []);
	return <></>;
};
`
then use dynamic import 
`
const DynamicComponent = dynamic(() => import("../components/vconsole"), {
	ssr: false,
});
`
In particular, the ssr parameter should be set to "false"
now, you can use vconsole in nextjs

**Comment by Poem7200** [comment]
> build a vconsole component `const VConsole = () => { useEffect(() => { ISDEV && new vconsole(); }, []); return <></>; };` then use dynamic import `const DynamicComponent = dynamic(() => import("../components/vconsole"), { ssr: false, });` In particular, the ssr parameter should be set to "false" now, you can use vconsole in nextjs

I've tried your method but nextjs return ReferenceError: XMLHttpRequest is not defined, and then I install xhr2 but still can't solve this problem…… could you show the demo?

**Comment by hsl727261250** [comment]
next.js ≥ 11

in `_app.tsx` file
``` typescript
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Script from 'next/script';
import 'weui';
import { MyProvider } from '../contexts'; // TODO del
import '../styles/globals.css'; // TODO del

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <MyProvider>
      <Head>
        <meta charSet='UTF-8' />
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </MyProvider>
    {/* @ts-ignore */}
    <Script src='https://unpkg.com/vconsole@latest/dist/vconsole.min.js' onLoad={() => { const vConsole = new window.VConsole() }} />
  </>
}

export default MyApp
```
