### ISSUE TITLE
依赖 cookie-storage 没兼容 escape 非英文字符的情况

### ISSUE THREAD

**Issue by id77** [Tencent/vConsole#509]
vConsole Version: 3.11.2

没兼容 cookie 含 escape 非英文字符的情况，使用到的 cookie-storage 好像没人维护了的。

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/9592236/154038117-ae48f977-70d3-43b4-96a3-c91121a7d790.png">

![1C377DC7EF3B27570E270EB4CBF75802](https://user-images.githubusercontent.com/9592236/154038239-af105e01-fd1c-4ec4-9669-9b4ed4cc98bf.jpg)

**Comment by Maizify** [comment]
谢谢反馈。我看看怎么处理一下。

**Comment by Maizify** [comment]
你的非英文 escape 字符是啥？按理说 escape 字符应该要被 `encodeURIComponent` 过才可被 set 入 cookie 的，cookie value中不应该存在这种字符吧。

**Comment by id77** [comment]
> 你的非英文 escape 字符是啥？按理说 escape 字符应该要被 `encodeURIComponent` 过才可被 set 入 cookie 的，cookie value中不应该存在这种字符吧。

比如某个地址 escape('广州天河')

**Comment by Maizify** [comment]
已在3.12.0中修复。
