### ISSUE TITLE
angular build error on latest version (3.11.2)

### ISSUE THREAD

**Issue by Evan7o** [Tencent/vConsole#512]
vConsole Version:3.11.2
Hi, we using ionic and vconsole develop app, before when using 3.4.0 version vConsole with develop environment, the ionic icon incorrect display, so we cry update to latest(3.11.2).
but some errors in **/node_modules/vconsole/dist/vconsole.min.d.ts** files.
`Error: node_modules/vconsole/dist/vconsole.min.d.ts:231:37 - error TS2307: Cannot find module 'svelte' or its corresponding type declarations.`
![image](https://user-images.githubusercontent.com/12377284/154450843-411c704c-a29d-4fbb-8195-4cf84e13d4d4.png)
![image](https://user-images.githubusercontent.com/12377284/154450941-8c5b3a43-1e13-46fe-9778-dd6af1b99ce0.png)
so, maybe we need to install these dependencies package?

**Comment by Maizify** [comment]
You don't need to install these dependencies, vConsole can be used directly.
The current way of generating `.d.ts` is not perfect, so bring these external dependencies.
Next I will try to remove these dependencies and make `.d.ts` more pure.
Until then you can try to ignore these errors.

**Comment by Evan7o** [comment]
OK, thanks for your reply
