### ISSUE TITLE
CDN资源加载异常缓慢

### ISSUE THREAD

**Issue by mingyong-g** [Tencent/vConsole#513]
vConsole Version:
https://cdn.bootcdn.net/ajax/libs/vConsole/3.9.0/vconsole.min.js

近期发现CDN链接加载异常缓慢，且发生频率较高，有时资源加载时间甚至长达15S

**Comment by Maizify** [comment]
你可以尝试使用其他CDN，如有问题可以反馈给CDN提供方。
https://unpkg.com/vconsole@latest/dist/vconsole.min.js
https://cdn.jsdelivr.net/npm/vconsole@latest/dist/vconsole.min.js

**Comment by mingyong-g** [comment]
破案了

[BootCDN 服务被违规网站使用遭误伤 ](https://blog.bootcdn.cn/bad-sites/)
2022年02月10日下午，由于有违规网站引用 BootCDN 上的文件链接，违规网站被举报后，BootCDN 也被误伤，域名被 CDN 厂商封禁，我们积极和 CDN 厂商协调解封事宜，同时在赞助商 极兔云 的协调下已将 BootCDN 服务迁移到新的 CDN 厂商处，目前 BootCDN 服务已经恢复。
