### ISSUE TITLE
v3.12.0 错误请求导致CPU暴增页面卡死

### ISSUE THREAD

**Issue by xuqianjin** [Tencent/vConsole#515]
vConsole Version:v3.12.0以上
使用axios发送请求..只要请求出现任意错误..CPU直接跑满
复现步骤:
```js
<button onClick={() => { axios.get('http://baidu.com'); }}>
        点击
</button>
```

![image](https://user-images.githubusercontent.com/12406066/157364388-5f42ddd9-6797-4531-b68c-f9738a6d0f11.png)

**Comment by Maizify** [comment]
axios版本呢？
另外vConsole和Axios的引入先后顺序是怎样的呢？

**Comment by xuqianjin** [comment]
> axios版本呢？ 另外vConsole和Axios的引入先后顺序是怎样的呢？

vconsole : 0.21.4
axios : 0.21.4
没有引入顺序..就umi创建的一个项目

**Comment by Maizify** [comment]
试一下3.14.0？这版重写了XMLHttpRequest的注入逻辑，看看是否还存在跟Axios的冲突。

**Comment by pocketChao** [comment]
遇到了同样的问题，返回的数据200多K 5000多条数据 直接卡死 cpu瞬间满了  js堆也好打  好久才会恢复

**Comment by Maizify** [comment]
> 遇到了同样的问题，返回的数据200多K 5000多条数据 直接卡死 cpu瞬间满了 js堆也好打 好久才会恢复

@pocketChao 如何复现呢？是瞬间返回5000个XHR吗？

**Comment by Maizify** [comment]
已经查明问题，是字符串处理有问题。

**Comment by Maizify** [comment]
已在v3.14.4中修复。
