### ISSUE TITLE
request headers看不到了

### ISSUE THREAD

**Issue by 1548583993** [Tencent/vConsole#522]
3.14.3，Network中，各个请求的Request Headers没有了

**Comment by 1548583993** [comment]
XHR

**Comment by Maizify** [comment]
麻烦提供一下可复现的case。

**Comment by 1548583993** [comment]
![111](https://user-images.githubusercontent.com/70678070/160799299-9f71b9ab-43cb-481e-ba29-d1bcde0647b0.jpg)
就是Request Headers看不到了，这里有配置项可以配置么

**Comment by Maizify** [comment]
header是在onReadyStateChange的时候取的，看来可能是这里有问题。从截图看，HTTP Status也丢了。我再查查看。

**Comment by 1548583993** [comment]
上面的图左边是最新版    右边是稍旧一些的。总之信息应该尽可能全面的。

**Comment by Maizify** [comment]
请问有没有用其他的网络库呢，比如Axios。或者你的业务框架里有无对XMLHttpRequest做改动？

**Comment by baiyoung** [comment]
通 request headers 看不到了

**Comment by 1548583993** [comment]
就是Axios，也没有什么特殊的改动。上面两个图是同一个项目里的两个类似的调用。

**Comment by 1548583993** [comment]
![222](https://user-images.githubusercontent.com/70678070/160834441-e35952b4-e0b5-483a-9319-dba3c76537f3.png)
同一个请求，三个版本的vconsole.（以前没有Response Headers，3.14.3有了）

**Comment by Maizify** [comment]
收到，我定位一下。

**Comment by Maizify** [comment]
@1548583993 @baiyoung 有无可复现的网址？我在本地无法复现。

**Comment by Maizify** [comment]
已定位到原因，在3.14.0时重写了XHR的代理逻辑，缺少代理了`setRequestHeader`方法导致未捕获到header。预计在3.14.4中修复。

**Comment by 1548583993** [comment]
感谢。
