### ISSUE TITLE
console.time无法打印时间

### ISSUE THREAD

**Issue by xuqianjin** [Tencent/vConsole#523]
vConsole Version: v3.14.3
```
console.time('a');
console.timeEnd('a');
```
无法打印时间

**Comment by Maizify** [comment]
如何复现呢？我这边是OK的。

<img width="399" alt="image" src="https://user-images.githubusercontent.com/215664/160972454-726e417f-d801-44cb-aa2e-87ffc03197fd.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/215664/160972431-a3363c70-e0af-4617-b8ed-62d5a990adbd.png">

**Comment by xuqianjin** [comment]
正常情况：
![image](https://user-images.githubusercontent.com/12406066/161055282-0264efd8-25e5-4b7a-a0b1-7e25b8a48448.png)
异常情况：
![image](https://user-images.githubusercontent.com/12406066/161055336-4768935a-b177-46dc-ba9e-95481af4c9e4.png)

**Comment by Maizify** [comment]
在已引入vConsole的前提下，在Chrome控制台内输入命令，无法复现。
time的逻辑已经很久没改过了，你看看旧版本有无问题？亦或是有其他地方的代码修改了time/timeEnd()？

<img width="235" alt="image" src="https://user-images.githubusercontent.com/215664/161194584-ed57ee46-f085-4116-b1b0-501fa386d36c.png">

**Comment by xuqianjin** [comment]
> 
开的无痕窗口...从v3.14.2开始..就没再打印了...就在你们demo上测试的..
![image](https://user-images.githubusercontent.com/12406066/161207611-e1d0bf0f-5c73-4643-be53-ab0d82cb72b5.png)

![image](https://user-images.githubusercontent.com/12406066/161207694-31ae7772-7df1-485a-a26d-7a0e1c4249d7.png)

**Comment by xuqianjin** [comment]
> 在已引入vConsole的前提下，在Chrome控制台内输入命令，无法复现。 time的逻辑已经很久没改过了，你看看旧版本有无问题？亦或是有其他地方的代码修改了time/timeEnd()？
> 
> <img alt="image" width="235" src="https://user-images.githubusercontent.com/215664/161194584-ed57ee46-f085-4116-b1b0-501fa386d36c.png">

**Comment by Maizify** [comment]
谢谢反馈。定位到是 3.14.2 修改构建逻辑引入的 bug。

**Comment by Maizify** [comment]
已在3.14.5发布。
