### ISSUE TITLE
v3.14.4 Cannot read properties of undefined (reading 'pluginList')

### ISSUE THREAD

**Issue by Gavin-Gao-Vegeta** [Tencent/vConsole#525]
环境 ：node14+vite+vue3+ts+容器化部署
问题描述：生成环境下打开页面就出现报错提醒。
v3.10.1不会出现这个问题。
![image](https://user-images.githubusercontent.com/46956309/161023123-b62c3113-8a88-42f7-9dd6-f7f124a00b81.png)
![image](https://user-images.githubusercontent.com/46956309/161023616-d38c4b55-0e40-4f76-95d1-120328282149.png)

**Comment by Maizify** [comment]
是否有做 SSR 之类的直出渲染？从内部逻辑上看，如果页内已有 id 为 `#__vconsole` 的元素，那么就不会初始化 `this.comInstance`，才会导致这个报错。

**Comment by Maizify** [comment]
应该是短时间内快速new了两次导致的。现在调整了下初始化时的判断逻辑，以避免这种情况。

**Comment by Maizify** [comment]
已在3.14.5发布。

**Comment by haledeng** [comment]
低端机型上，这个问题还是存在

**Comment by yoyo837** [comment]
~Chromium 52 仍然有这个问题. Android 7~

我这边自检确实是重复`<script>` 引入并且重复 `new` 了.

**Comment by qtanran** [comment]
vite + vue3 + vconsole3.15.1
在ios17还会出现这个问题

**Comment by qtanran** [comment]
![64dbea709d48e2930f51685100b8e41](https://github.com/Tencent/vConsole/assets/48440870/cdbe62b1-0745-4558-88e7-6edf979e3502)
