### ISSUE TITLE
3.14.0之后的版本，会导致wavesurfer.js无法使用

### ISSUE THREAD

**Issue by lidaweicn** [Tencent/vConsole#527]
vConsole Version: 3.14.0 - 3.14.4

3.13.0 版本没问题，
3.14.0 之后的版本会导致wavesurfer.js无法使用，

通过调试发现，在wavesurfer load 音频文件时，fetchFile 函数返回错误导致的，
但是在调试时 fetch 请求已经返回正确的数据，但是在进入 v console 之后就出现一个报错信息
TypeError: Failed to fetch

3.14.0 的修改 Refactor(Network): Use proxy on fetch(). 是否跟这个有关 ？#518

**Comment by Maizify** [comment]
可能会有影响，因为3.14.0开始修改了fetch的代理逻辑。
但我使用wavesurfer官网的示例代码，没有复现你说的报错，fetch正常下载了文件。
有无可复现的代码片段或网页？

```javascript
  var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'violet',
    progressColor: 'purple'
  });
  wavesurfer.load('./data/a.wav');
```

**Comment by lidaweicn** [comment]
我用的音频是其他网址的音频，不是在项目路径下，有时间我调试一下

**Comment by lidaweicn** [comment]
3.14.5版本已修复
