### ISSUE TITLE
版本升级后js报错 undefined is not an object （evaluating 'this.resp.body.getReader')

### ISSUE THREAD

**Issue by tangyefei** [Tencent/vConsole#531]
版本升级后js报错 undefined is not an object （evaluating 'this.resp.body.getReader')

![image](https://user-images.githubusercontent.com/3982987/162626276-953b77a7-9bfe-4956-bcea-6c09e312608e.png)

h5运行在应用容器中（钉钉、公司自主开发的App），类型OPTOINS的请求在vConsole中的response表现为上述形式，此前运行良好，新的发版会报错，推测是改版后无法争取处理OPTIONS请求。

**Comment by Maizify** [comment]
感谢反馈。
我推测是 OPTIONS 类型的请求，在某些浏览器或 webview 中，不会返回 response body，所以挂了。
我先对这部分逻辑做个空值保护。

**Comment by Maizify** [comment]
已在3.14.6中发布。
