### ISSUE TITLE
iOS9 的兼容性问题

### ISSUE THREAD

**Issue by ACERY1** [Tencent/vConsole#532]
在 iOS 9的机器上看不到 vConsole 的绿色button，在其他机器上就能看到，这里是不是有什么兼容性的问题

**Comment by ACERY1** [comment]
> 本广泛使用了Proxy等特性，iOS 10才开始支持。

用dev分支下的构建产物能够支持iOS9吗

**Comment by ACERY1** [comment]
或者有没有哪个老版本的是支持 iOS9的，因为我记得之前在iOS9上用到过

**Comment by Maizify** [comment]
> 用dev分支下的构建产物能够支持iOS9吗

不能，dev分支是最新的版本。

**Comment by ACERY1** [comment]
试了一下 2.5.1 的版本是可以跑的。

**Comment by Maizify** [comment]
2.5.1太低了，如果你只是想看log倒是无所谓，但是可能有不符合预期的效果。
稍微新一点的（也是好多年前），可以从3.4.1、3.3.4这个范围尝试。
