### ISSUE TITLE
在企业微信PC版中点击事件异常

### ISSUE THREAD

**Issue by Zcyisabigman** [Tencent/vConsole#534]
vConsole Version: 3.14.5
单击无法展开Network 等 面板中的项
长按鼠标有时可展开成功

**Comment by Maizify** [comment]
手头上没有 Windows，我在 Mac 版企业微信的网页中是正常的。
有无可复现的网页呢？

**Comment by Zcyisabigman** [comment]
> 手头上没有 Windows，我在 Mac 版企业微信的网页中是正常的。 有无可复现的网页呢？

正好， 我们这边macOS（M1） 和 windows 都出现了这个问题。 暂时没有可供复现的简易demo。
macOS 12.3.1 (21E258) 
企业微信 版本 4.0.3.70108

**Comment by Maizify** [comment]
http://wechatfe.github.io/vconsole/demo.html
我在M1 Mac上访问Demo，没有复现这个问题。你看看上面这个Demo可否复现？

**Comment by Zcyisabigman** [comment]
> http://wechatfe.github.io/vconsole/demo.html 我在M1 Mac上访问Demo，没有复现这个问题。你看看上面这个Demo可否复现？

我试了你提供的这个网页， 没有问题。 请问这网页里面的vConsole是哪个版本的呢？

**Comment by Maizify** [comment]
是最新的，当前为3.14.5。
所以可能得检查下业务页面有无影响。

**Comment by Zcyisabigman** [comment]
> http://wechatfe.github.io/vconsole/demo.html 我在M1 Mac上访问Demo，没有复现这个问题。你看看上面这个Demo可否复现？

现在猜测可能是有其他依赖导致了冲突，后续我这边会排查其他依赖问题，我在这里贴一下现在出现问题的项目的依赖列表：
<img width="323" alt="image" src="https://user-images.githubusercontent.com/25562693/163344167-18fb4562-5932-4a87-9f51-6021998f1560.png">

**Comment by Maizify** [comment]
你这里vConsole是3.4.0呀，是很老的版本了。

**Comment by Zcyisabigman** [comment]
> 你这里vConsole是3.4.0呀，是很老的版本了。

是的，我恢复为老版本点击功能才正常， 我的意思是其他依赖可能和新版有冲突，我这边会自行排查。 
感谢。

**Comment by Maizify** [comment]
好的，若有结论、需要vConsole修改的，也麻烦告知下，谢谢。

**Comment by Zcyisabigman** [comment]
> 好的，若有结论、需要vConsole修改的，也麻烦告知下，谢谢。

我现在怀疑 是     "@vant/touch-emulator": "^1.3.2",  这个依赖引起的问题， 现在准备去除这个依赖再试试。
如果确定是这个依赖的问题的话， 那么可能得想办法把vConsole初始化到指定节点下，因为 @vant/touch-emulator  提供的禁用方式是在节点上添加属性：
<img width="901" alt="image" src="https://user-images.githubusercontent.com/25562693/163346175-52f3757a-5c8f-467b-9d69-abe29fc9643b.png">

参考： 
https://www.skypack.dev/view/@vant/touch-emulator

**Comment by Zcyisabigman** [comment]
现在已确定是与 @vant/touch-emulator 插件不兼容。

**Comment by Zcyisabigman** [comment]
document.getElementById('__vconsole').setAttribute('data-no-touch-simulate', '')
