### ISSUE TITLE
在 Android webview 引入后，界面显示空白， 无任何输出

### ISSUE THREAD

**Issue by AchioZhai** [Tencent/vConsole#536]
在主 index.html 中加入如下代码，vConsole 按钮显示在主页面，点开后为空白
vConsole版本：v3.4.1
手机系统：鸿蒙 2.0
不知道哪里出了问题，希望可以得到帮助，感谢您
```
<script src="vconsole.min.js"></script>
        <script>
  // 初始化
  var vConsole = new VConsole();
  vConsole.log('Hello world');
</script>
```

显示空白图片如下所示：
![WechatIMG4784](https://user-images.githubusercontent.com/19261122/164589527-83d40e05-997e-44ea-ae6a-e87b355f4f41.jpeg)

**Comment by Maizify** [comment]
3.4.1有点旧，使用最新版本试试看？

**Comment by AchioZhai** [comment]
> 3.4.1有点旧，使用最新版本试试看？

尝试更新到最新版本了，已解决问题，感谢
