### ISSUE TITLE
How to uninstall vConsole on google chrome ?

### ISSUE THREAD

**Issue by Fiiree** [Tencent/vConsole#537]
Hi, i want to uninstall vConsole on chrome, idk where i have download it. If someone can help me, thanks.
![azerty](https://user-images.githubusercontent.com/104796378/166326393-2bf34174-537b-41c4-aa37-809ae3a9e48d.png)

**Comment by robotstacy** [comment]
dude, i dont even remember install it. What tf

**Comment by robotstacy** [comment]
YO. So I removed all cookies, and cleared browser history and this is GONE. IDK if it is affiliated w/ tencent, but I am concerned about script injection. I looked through my filesystem, and also found a package "fortawesome" installed globally.
Misspelled font awesome. Made by 'tencent'

**Comment by robotstacy** [comment]
IDK if this is affiliated w/ tencent officially, but I am reinstalling my OS after recent chrome data breaches. This is ridiculous

**Comment by robotstacy** [comment]
Honestly Fiiree id reinstall your OS this feels fishy

**Comment by Maizify** [comment]
vConsole is installed by the developer of the web page you are visiting, this has nothing to do with Chrome or the OS.

If the web page is your own, but vConsole appears, maybe a dependency package of your web page has vConsole installed and forgot to close it when publishing. If this is the case, please check your dependencies and contact the relevant authors.
