### ISSUE TITLE
Android Webview 无法动态注入 vConsole.min.js

### ISSUE THREAD

**Issue by strange-qwq** [Tencent/vConsole#546]
vConsole Version: 3.14.6

错误内容：
点击vConsole浮窗AS控制台报错：`Unable to preventDefault inside passive event listener invocation.`，且没有弹出网页控制台

复现步骤：
1.直接注入`script`标签或下载`http://cdn.jsdelivr.net/npm/vconsole@3.14.6/dist/vconsole.min.js`到安卓本地并使用`evaluateJavascript`方法读取js均可;
2.使用`loadUrl`方法执行`new VConsole()`;
3.点击出现的VConsole浮窗

关键代码：
![image](https://user-images.githubusercontent.com/73089181/173490967-ca6c6d02-ebd5-4b9b-8698-99e25eaa3fa9.png)

**Comment by Maizify** [comment]
我这里本地没有条件验证。根据这个 error 的表现，应该是 touch 事件中使用了 `preventDefault()` 引起的，因此这里尝试强制使用 `passive: false` 模式来避免报错。楼主可以试下这个版本。
