### ISSUE TITLE
console里的css，使用%c的特性一定要加空格是为什么

### ISSUE THREAD

**Issue by SoonIter** [Tencent/vConsole#549]
vConsole Version:3.6.1
![image](https://user-images.githubusercontent.com/79413249/175614385-729bc979-585b-4ee7-84ce-371fe6f4907c.png)
![image](https://user-images.githubusercontent.com/79413249/175614520-e2472e04-cfb3-41b7-8243-0f5f2458f592.png)

**Comment by SoonIter** [comment]
![image](https://user-images.githubusercontent.com/79413249/175812385-3432a354-a2ae-4180-952c-e8944e9a4dfd.png)

去源码里看了一下，确实有%c这个特性，现在已经可以触发了，但是为什么一定要有个空格才可以触发

**Comment by SoonIter** [comment]
#550

**Comment by Maizify** [comment]
如PR里所说，主要是为了方便匹配。

**Comment by SoonIter** [comment]
> 如PR里所说，主要是为了方便匹配。

与原生console行为不一致了，如果非要这么做的话就在文档里写一下吧
