### ISSUE TITLE
手动编辑 storage 面板中的 cookie 失败

### ISSUE THREAD

**Issue by ShiRouMi** [Tencent/vConsole#557]
vConsole Version: 3.14.6
比如存在 cookie 在 `domain` 为 `.a.b.com` 下
```js
user_ss: abc
```
手动编辑该 `cookie` ，修改值为 `def`

面板下 `cookie` 值没有改变

命令行 `document.cookie` 取值得到 `user_ss=def; user_ss=abc`
命令行 `document.cookie='user_ss=def; path=/` 能重写该cookie 

显然手动编辑该域下的 cookie 失败，反而重写了一个本地的cookie
建议 storage 面板下有 domain path maxAge 等属性

**Comment by Maizify** [comment]
不好搞，前端拿不到domain等信息。因此在面板中编辑cookie，也只能影响到当前域下的cookie。
