### ISSUE TITLE
微信小游戏使用vConsole提示“fetch is not defined”

### ISSUE THREAD

**Issue by xiezhizhao** [Tencent/vConsole#558]
### vConsole Version:
vConsole   3.14.6

### 安装
在cocoscreator下使用npm install vconsole

### 初始化：
import VConsole from 'vconsole';
const vconsole = new VConsole();

### 报错
发布【微信小游戏】，运行报错，浏览器vConsole运行正常。

```
ReferenceError: fetch is not defined
    at vconsole.min.js:18
    at vconsole.min.js:18
    at vconsole.min.js:18
    at vconsole.min.js:18
    at vconsole.min.js:18
    at CjsLoader._load (cjs-loader.mjs:78)
    at CjsLoader._tryModuleLoad (cjs-loader.mjs:63)
    at CjsLoader._require (cjs-loader.mjs:42)
    at CjsLoader.require (cjs-loader.mjs:27)
    at Object.execute (vconsole.min.mjs?cjs=&original=.js:7)(env: Windows,mg,1.06.2208010; lib: 2.25.3)
```

### 截图：
![image](https://user-images.githubusercontent.com/40783070/184618572-4593bd57-001e-4151-958b-8a18a58bf503.png)

**Comment by ManiaciaChao** [comment]
小游戏/小程序环境里没有 fetch API，网络请求走 wx.request。network 面板会试图 hook fetch，禁用即可。当然，你也可以自行封装一个 fetch（或引入 polyfill）。

```typescript
// disable network, element & storage plugins
const vConsole = new VConsole({ defaultPlugins: ['system'] })
```
