### ISSUE TITLE
安卓手机开启vConsole导致资源偶尔加载错误

### ISSUE THREAD

**Issue by mmhforjavaweb** [Tencent/vConsole#575]
css文件加载报错：Resource interpreted as Stylesheet but transferred with MIME type text/plain，导致页面样式错乱
css文件偶发变成这样

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/19813166/198234535-24252a33-31fd-4372-9c0e-eea43aae107a.png">

关闭vConsole则一直正常

测试环境：企业微信

**Comment by Maizify** [comment]
vConsole并不会干涉CSS加载。截图里的代码片段也不是vConsole的。
你可以检查一下是不是别的地方有问题。
