### ISSUE TITLE
setting 'switchButtonPosition' undefined

### ISSUE THREAD

**Issue by stephenliu1944** [Tencent/vConsole#579]
vConsole Version: 3.14-3.15
when I use switchButtonPosition to set VConsole's position, it throw "setting 'switchButtonPosition' undefined", 
```
let vc = new VConsole();
vc.setSwitchPosition(20, 20);
// or
new VConsole();
VConsole.instance.setSwitchPosition(20, 20);
```

![image](https://user-images.githubusercontent.com/5137237/200246964-7a077065-6752-41dc-88da-17c81d2a4b70.png)
I find that this.compInstance is undefined.

**Comment by Maizify** [comment]
You should call this method in the `onReady()` callback. Because `new vConsole()` is asynchronous.
