### ISSUE TITLE
使用vConsole, 报 XMLHttpRequest is not defined 错误

### ISSUE THREAD

**Issue by hedanto** [Tencent/vConsole#588]
vConsole Version:3.15.0
使用vConsole, 报 XMLHttpRequest is not defined 错误
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/8426839/205028115-dccdfa6f-494a-428e-b846-4cb8ffb330f5.png">

**Comment by zx013** [comment]
我在windows使用next.js的时候vconsole也报了这个错误

**Comment by zhangdimelody** [comment]
+1 请问解决了吗，我也遇到了同样的问题

**Comment by jyjin** [comment]
Nextjs vconsole 遇到这个问题，请问解决了么

**Comment by nnmax** [comment]
NextJS 会在服务端执行一遍代码，而 VConsole 依赖于浏览器环境，所以需要在 `useEffect` 中实例化：

```tsx
// src/pages/_app.tsx
// 或者 /src/app/layout.tsx
import VConsole from 'vconsole'

function Root() {

  useEffect(() => {
    const vconsole = new VConsole()
    return () => {
      vconsole.destroy()
    }
  }, [])

  return () => <div />
}
```

**Comment by jyjin** [comment]
邮件我已收到，谢谢！

**Comment by limjinda** [comment]
remove import from the top of file and useeffect instead

```
useEffect(() => {
    const setupVConsole = async () => {
      const VConsole = (await import('vconsole')).default
      new VConsole()
    }
    setupVConsole()
  }, [])
```

**Comment by jyjin** [comment]
邮件我已收到，谢谢！
