### ISSUE TITLE
Can't add event listener at plugin's ready event when upgrade vConsole version to 3.15.0

### ISSUE THREAD

**Issue by johnscliang** [Tencent/vConsole#591]
```js

export default function initHelperPlugin(vconsole, VConsolePlugin) {
  let plugin = new VConsolePlugin('helper', 'Helper');
  plugin.on('renderTab', function(callback) {
    let html = `
    <div>env: ${import.meta.env.MODE}</div>
    <div style='margin-top: 2em;text-align:center'>
      <button id='vconsole_bt_close_vconsole' style='font-size: 32px;'>
      关闭VConsole
      </button>
    </div>
    `
    callback(html);
  });
  plugin.on('ready', function() {
    document.querySelector('#vconsole_bt_close_vconsole').addEventListener('click', function() {
      vconsole.destroy();
    });
  });
  return plugin;
}

```
    document.querySelector('#vconsole_bt_close_vconsole') will come out error with "helper.vconsole.plugin.js?t=1671097953842:15 Uncaught (in promise) TypeError: Cannot read properties of null"

**Comment by johnscliang** [comment]
GitHub好卡。。。补充下说明，这个代码在旧版本（3.14.x）是可以的，ready之后可以直接querySelector，升级到最新就不行了。

**Comment by johnscliang** [comment]
可以在settimeout中执行没问题，下一个循环对吧。但是这样处理感觉很不爽，请帮忙看看是bug还是我的写法有问题

**Comment by johnscliang** [comment]
3.14.6 还可以，3.14.7和之后的版本就会报错。

**Comment by Hani1obaid** [comment]
F

**Comment by ManiaciaChao** [comment]
是 bug。从这个提交 [#c8d312a](https://github.com/Tencent/vConsole/commit/c8d312a0a7b7ae4fa9dfbb09e670eb652459c0d9?diff=split#diff-a4510eaba83767eb16844f68f265264eeaf913d4e6cadecaa9f17c06883e478cR309)开始，这里不再是同步渲染；但 ready 事件仍然是同步发出的。
在修复之前，需要使用 setTimeout。

**Comment by Maizify** [comment]
Thanks, I've fixed it using another way, see original issue #591.

**Comment by Maizify** [comment]
当初使用 setTimeout 来渲染插件，使同步变成异步，是存在问题的。
我改了下写法，现在应该是同步的了。
