### ISSUE TITLE
vconsole按钮设置颜色

### ISSUE THREAD

**Issue by fqycugb** [Tencent/vConsole#594]
vConsole Version:
vconsole按钮的颜色可以修改吗

**Comment by ManiaciaChao** [comment]
结论：可以。
目前尚未开放自定义 switch 颜色的 API，但可以通过覆盖该全局 CSS 变量来实现：

https://github.com/Tencent/vConsole/blob/05d80398bae35e793774f74e3c052b4e530e293a/src/core/style/theme.less#L21

示例：

```css
#__vconsole {
    --VC-BRAND: red!important;
}
```
