### ISSUE TITLE
无法显示使用loglevel输出的log

### ISSUE THREAD

**Issue by jingzhongchangan** [Tencent/vConsole#603]
vConsole Version: latest

目前项目使用 loglevel (https://www.npmjs.com/package/loglevel) 控制log输出的level（目的是在prod环境关闭所有log）。但输出的log可以显示在浏览器console中，无法显示在vconsole中。
请问如何支持把loglevel输出的内容显示在vconsole中，或者vconsole是否支持通过level控制log的开关？

**Comment by Maizify** [comment]
看起来loglevel用的是自己实现的log。而vConsole用的是浏览器原生的console.log。
如果需要结合使用，可以考虑自己桥接一下。
