### ISSUE TITLE
这里有错误，不知道为什么 addPlugin

### ISSUE THREAD

**Issue by youyongba** [Tencent/vConsole#608]
vConsole Version: 3.15.0
vconsole.min.js:10 Uncaught TypeError: e.trigger is not a function

代码: 

// 调研vConsole

import vConsole, {VConsolePlugin} from 'vconsole';

function List(props) {

  useEffect(() => {

    const vconsole = new vConsole();
    const myPlugin = {
      name: 'MyPlugin',
      onAdd: () => {
        console.log('My Plugin added');
      },
      onRemove: () => {
        console.log('My Plugin removed');
      },
    };
    vconsole.addPlugin(myPlugin);

    return () => {
      const myPlugin = vconsole.getPlugin('MyPlugin');
      vconsole.removePlugin(myPlugin);
      vconsole.destroy();
    };

}, [])

  return (
    <>
    
      <div></div>

    </>
  )
}

export default List

**Comment by Maizify** [comment]
请按文档中的方法来创建 plugin 对象，你现在手动拼的 `myPlugin` 对象是不对的。
