### ISSUE TITLE
在Mobile Safari 13.0.5版本中不能使用

### ISSUE THREAD

**Issue by limka0129** [Tencent/vConsole#610]
vConsole Version:
3.15.0

操作系统版本：iOS 13.3.1

![image](https://user-images.githubusercontent.com/73980688/224631305-73d4a050-b517-4813-9587-48e3dc5557b5.png)

弄了一个空白页面，基本可以排除其他影响~
很奇怪，只有这个版本不行，别的Safari版本都可以用

**Comment by yuguaa** [comment]
ios 10, 俺也一样

**Comment by fxfSean** [comment]
> ios 10, 俺也一样

@limka0129 @yuguaa 
我也在我的IOS 系统版本12.4.5测试机上遇到了这个问题，连接电脑后发现报这个错误：
`ReferenceError: Can't find variable: ResizeObserver`
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18061579/232364998-5ac6a4e6-669f-48cc-8814-6b362d410f58.png">

然后这个API在IOS 13以下是不支持的
<img width="583" alt="image" src="https://user-images.githubusercontent.com/18061579/232361079-33c9e97e-23e2-4e36-92a8-ecb7500239a9.png">
虽然我在项目的`package.json`中配置了`browserslist`：
`"ios_saf >= 10",
    "Safari >= 10",`
但是打包文件中依旧出现了这个`ResizeObserver`，搞不明白。
最后解决办法是在`package.json`中添加这个依赖：
`"resize-observer": "^1.0.4",`
然后在使用Vconsole的位置**之前**安装：
> 注意是之前
``` import { install } from 'resize-observer';
if (!window.ResizeObserver) {
  install();
}
import Vconsole from 'vconsole' ```

**Comment by yuguaa** [comment]
thanks，但是我已经转向了g6了

**Comment by Maizify** [comment]
iOS 13.3 不兼容 ResizeObserver 确实会导致这个问题。
我加了个 ResizeObserverPolyfill，理论上可以规避掉这个情况（会缺失实际能力，但不影响日志功能）。但我手头上没有可测试的设备，有条件的朋友可以试下。

**Comment by QinZhen001** [comment]
遇上了 ResizeObserver 问题+1  android 系统 6.x
