### ISSUE TITLE
查看network时，看不到response headers的内容

### ISSUE THREAD

**Issue by billsking** [Tencent/vConsole#614]
查看某个请求时，有的时候需要查看响应头的内容， 比如cookie、traceid等，但目前vConsole不支持，希望能支持下，或者可以由开发者自定义。

**Comment by Maizify** [comment]
现在是支持显示Response Headers的。如果你那边没显示，有没有可复现的页面，我看看？

<img width="399" alt="image" src="https://github.com/Tencent/vConsole/assets/215664/47c7b955-734f-4667-bbc7-7fa38460e37a">

**Comment by billsking** [comment]
问题解决了， 是因为后端服务在跨域场景下默认仅显示常用的7个，需要手动配置下要显示的header.
参考：https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header
