### ISSUE TITLE
前端进行SSE流式传输数据时报错length未定义

### ISSUE THREAD

**Issue by ethanz-code** [Tencent/vConsole#669]
vConsole Version:
3.15.1

Error Report:
> Error:  TypeError: Cannot read properties of undefined (reading 'length')
    at vconsole.js?v=d40a7ecd:6622:70
    at async getBytes (@microsoft_fetch-event-source.js?t=1710771233311&v=d40a7ecd:7:21)
    at async create (@microsoft_fetch-event-source.js?t=1710771233311&v=d40a7ecd:161:9)

**Comment by liyao1520** [comment]
一样+1

**Comment by JiangGuangqing** [comment]
一样+2

**Comment by grp-qianyashi** [comment]
+1，我把文件下下来了，将对应部分的判空逻辑修改了下就ok了
![image](https://github.com/user-attachments/assets/95d43128-6cd2-41d5-8e2f-f8fd284b9d10)

**Comment by jiezhiyong** [comment]
手动下载 js文件，查找Uint8Array关键字，将"if(t){var r=new Uint8Array(t.length+o.value.length)" 改为 "if(t&&o.value){var r=new Uint8Array(t.length+(o.value||[]).length)"

**Comment by milo-wjh** [comment]
这个issue关了 但是官方好像也没修复啊

**Comment by ding-js** [comment]
用 pnpm 的可以使用 pnpm patch 指令来修改 node_modules 内的代码，还是希望官方可以修复这个问题
