### ISSUE TITLE
移动设备，Network返回response是[Object blob]

### ISSUE THREAD

**Issue by memotail** [Tencent/vConsole#78]
为了方便调试，添加了vConsole，其他功能都完整，恰恰是Network在移动设备中，返回对象是blob，所以解析不出json。

iphone5s(ios10)，cordova打包到本地，请求返回是[Object blob]，而相同代码，在chrome浏览器是JSON的。

**Comment by Maizify** [comment]
请问方便截图看一下不？

**Comment by memotail** [comment]
截图方面，有点麻烦。

Network => 某个请求点开 =>Response => [object Blob]

我使用的是fetch api，在chrome浏览器打开是没问题的，而cordova打包后，就会出现这个[object Blob]，而不是JSON，估计就这样转换JSON出这个问题。

**Comment by Maizify** [comment]
header 里的 content-type 是啥呢？

**Comment by Maizify** [comment]
检查了下，也有可能是你的框架改变了 response 的类型。
方便的话，可以加以下 Q 群来沟通： 497430533

**Comment by chaiyanlin** [comment]
发起jsonp请求的时候Content-Type:application/json; charset=utf-8，也会出现>Response => [object Blob]

**Comment by deepcoldy** [comment]
可以试一下 我修改过的vconsole
https://martin-upload.b0.upaiyun.com/web/2017/03/fcf60909310de3396108a2ca3870c59f.js

**Comment by Maizify** [comment]
v3.0.0已处理。

**Comment by yangqihang521** [comment]
我也出现了这个问题，v3.3.0和v3.0.0都有问题

**Comment by duxiaofeng-github** [comment]
3.3.4同样有这个问题

**Comment by wjyzhixing** [comment]
3.7.0也有这个问题get请求返回
![image](https://user-images.githubusercontent.com/36620969/122637178-cd179c00-d11f-11eb-8ffe-50e89d29ab9c.png)

**Comment by jazz0522** [comment]
>   #@`
Duplicate of #`

**Comment by yushilong** [comment]
![image](https://user-images.githubusercontent.com/5087094/224216335-149fcc93-6185-4f6d-be6a-829f44a2ebb1.png)
the same!!!

**Comment by yushilong** [comment]
![image](https://user-images.githubusercontent.com/5087094/224216587-760a1ccb-2b83-443e-bd1b-32790d56e49b.png)
"vconsole": "^3.15.0",   一样的问题！！！！
