### ISSUE TITLE
使用 vue-resource 时无法捕捉到网络请求

### ISSUE THREAD

**Issue by Maizify** [Tencent/vConsole#80]

**Comment by LouisKai** [comment]
提些体验上的问题
1.vconsole控制台这里的command...光标没有居中
2.command代码输入没有自动补全或者提示
3.查看内部属性时点击>都会触发一次键盘弹出，遮盖了大部分界面，每次都要点击折叠有点麻烦

**Comment by deepcoldy** [comment]
@LouisKai 问楼主解决了吗

**Comment by Maizify** [comment]
v3.0.0已处理。
