### ISSUE TITLE
Network中状态永远是Pending

### ISSUE THREAD

**Issue by lsbrucelincoln** [Tencent/vConsole#87]
请问，我的Network面板里状态都是pending，这是什么原因呢？
![image](https://cloud.githubusercontent.com/assets/13454603/21536727/698cfac4-cdc1-11e6-90ef-014b20fc1b62.png)

**Comment by Maizify** [comment]
有无可体验的网址？我看下。

**Comment by lsbrucelincoln** [comment]
http://www.qqchou.org/qqcmobile/pages/detailPage_t8.html?event_id=443  @Maizify

**Comment by Maizify** [comment]
v3.0.0已处理。
