### ISSUE TITLE
Network中面板中所有请求状态永远是Pending

### ISSUE THREAD

**Issue by imsomnus** [Tencent/vConsole#96]
Network中面板中所有请求状态永远是Pending

**Comment by laserw9** [comment]
我的也是，ios手机 Safari浏览器， Response 显示是 undefined

**Comment by huige555551** [comment]
我的也是，ios手机 Safari浏览器， Response 显示是 undefined

**Comment by Missup** [comment]
import方式引入vconsole请求永远是pending，怎么解决

**Comment by Maizify** [comment]
v3.0.0已处理。

**Comment by chenhebing** [comment]
使用的是vconsole-webpack-plugin，手动升级vconsole 3.1版本，vue 2.5.2，axios 0.17.1 
依然存在这个问题，能否帮忙看下，谢谢
