### ISSUE TITLE
用es6的方式载入，页面崩溃

### ISSUE THREAD

**Issue by foxpsd** [Tencent/vConsole#98]
先npm安装，再用es6的模块方式载入：
`import vconsole from 'vconsole'`
页面直接崩溃。
我甚至没有调用vconsole的方法。
是vconsole暂时不支持这种载入方式吗？

**Comment by Maizify** [comment]
能看到报什么错误吗？

**Comment by Iamlars** [comment]
在webpack配置文件中这样使用：
````javascript
    const vConsolePlugin = require('vconsole-webpack-plugin');
    plugins: [
        new vConsolePlugin({
            enable: true
        }),
    ],
````
页面中会自动注入vConsole。

**Comment by muzi131313** [comment]
@livoras 不是先安装，再使用么？webpack不用配置吧。npm install vconsole --save --dev；然后直接require('vconsole')，import没有尝试
